### ISSUE TITLE
Cookies not set/saved in Browser

### ISSUE THREAD

**Issue by johandanforth** [OfficeDev/Office-Add-in-samples#124]
**URL of sample**

https://github.com/OfficeDev/PnP-OfficeAddins/tree/3ce0e1b74152dbbe8306a091696bc4455c04c0a1/Samples/auth/Office-Add-in-Microsoft-Graph-ASPNET

**Describe the bug**

Note: The sample works fine in Windows Outlook, but not in Web Outlook in a browser.
The code sample uses http cookies to keep track of the state keys, but cookies are never saved when running in a web browser. The request to read the cookie returns null every time. This is the code part in Session.cs that doesn't work anymore. Tried in Chrome and Edge:

```` c#
        public static string GetUserAuthStateId(HttpContextBase ctx)
        {
            string id;
            if (ctx.Request.Cookies[SessionKeys.Login.UserAuthStateId] == null)
            {
                // Convert GUID to a string and format as numeral to remove hyphens.
                id = Guid.NewGuid().ToString("N");
                ctx.Response.Cookies.Add(new HttpCookie(SessionKeys.Login.UserAuthStateId)
                {
                    Expires = DateTime.Now.AddMinutes(20),
                    Value = id
                });
            }
            else
            {
                id = ctx.Request.Cookies[SessionKeys.Login.UserAuthStateId].Value;
            }

            return id;
        }
````

**To Reproduce**

1) Download and run the sample. 
2) Click "Connect to Office 365" button
3) Click "Get Onedrive File Names"
4) Get an exception here:

```` c#
            var filesResult = await ODataHelper.GetItems<ExcelWorkbook>(fullWorkbooksSearchUrl, token.AccessToken);
````

because the cookie is never returned from request. 

**Expected behavior**

I expect the code line in HomeController - Index() to return the state-id:

```` c#
            var userAuthStateId = Settings.GetUserAuthStateId(ControllerContext.HttpContext);
````

**Environment**
- Platform [PC desktop, Mac, iOS, Office Online]: PC
- Host [Excel, Word, PowerPoint, etc.]: Outlook Web
- Operating System: Windows 10
- Browser (if using Office Online): 
  - Google Chrome Version 88.0.4324.190
  - Microsoft Edge Version 89.0.774.45
  - Microsoft Edge Canary Version 91.0.822.0

**Additional context**

The sample is not modified at all. I've also tried to use Session state instead of cookies, but since Session uses cookies, there's no difference. I'm not using any 3rd party plugins for the browsers and I have a vanilla Edge installation with no changes to the settings.

**Comment by ElizabethSamuel-MSFT** [comment]
@johandanforth Thanks for letting us know about this.

@davidchesnut Can you take a look?

Thanks.

**Comment by davidchesnut** [comment]
Hi @johandanforth, Sorry this has taken so long. I was working on a PR to update this sample, but we're changing our strategy to rely on the existing [Microsoft identity samples](https://learn.microsoft.com/azure/active-directory/develop/sample-v2-code).

The Office Add-in Microsoft Graph ASP.NET sample will be remapped to https://github.com/Azure-Samples/ms-identity-aspnet-webapi-onbehalfof That sample should also give you control over using cookies, or not.
 
We'll be posting some updated guidance on how you can update the identity samples to use the Office dialog API soon.

**Comment by johandanforth** [comment]
Hi @davidchesnut and thanks for the update. The problems I had this long ago actually made me drop everything until everything was more "ready". But the need is still there - we have an old, quite complex, Outlook addin written in c# that needs to be overhauled. I was hoping we could rewrite it using this technique...

**Comment by johandanforth** [comment]
Thanks @davidchesnut , I did not know of that sample, I will for sure give it a go, as soon as I get some time for it. Cheers. We sure want to move away from our old (but still working fine) Outlook add-in, because that particular add-in has grown into something ugly 😉

**Comment by johandanforth** [comment]
> Hi @johandanforth, If you haven't seen it already you may be interested in the [Outlook Blazor sample](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/blazor-add-in/outlook-blazor-add-in) that @elegault contributed. It allows you to keep the logic portions of your code in c#, although the UI will still need to be in JavaScript.

Sorry to say, the outlook blazor sample isn't working. I get this error in both desktop and web mode. Have tried with and without two-factor auth, same error:
![image](https://user-images.githubusercontent.com/527037/202011496-94463724-d24f-4a52-bb87-cab7b1654bc7.png)

**Comment by davidchesnut** [comment]
I sideloaded the sample to Outlook on web, and Outlook on Windows and it seems to load and run fine.

Can you try again after [clearing the Office cache](https://learn.microsoft.com/office/dev/add-ins/testing/clear-cache)?

Thanks!
David

**Comment by johandanforth** [comment]
I will try in a few minutes, forgot to clear the cache! I've not looked at this architecture since I reported that issue a long time ago now. Sorry.

/Danforth
________________________________

**Comment by davidchesnut** [comment]
Will close for now, but @johandanforth please reopen if there is still any ongoing issues. Thanks!
