### ISSUE TITLE
webpack.config.js example for Excel keyboard shortcuts

### ISSUE THREAD

**Issue by FreeSoftwareServers** [OfficeDev/Office-Add-in-samples#241]
The sample for excel keyboard shortcuts (https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/excel-keyboard-shortcuts) talks about 

> "Ensure the new file is properly bundled by configuring the webpack.config.js file."

 I haven't had to edit that file yet and would love more details on how to configure it.

**Comment by AkhileshShah-MS** [comment]
@dingjin-ms Could you please help with the request here?

**Comment by davidchesnut** [comment]
The sample is not using webpack, so I'll remove that info. But if you were using it you'd need to add something like the following to the plugins section of webpack.config.js. This would ensure the shortcuts.json file is part of the webpack bundle when you deploy to your web server.

```javascript
 new CopyWebpackPlugin([
        {
          to: "shortcuts.json",
          from: "./src/shortcuts.json"
        }
      ]),
```

Hope this helps,
David
