### ISSUE TITLE
home.js it should read the webconfig value?

### ISSUE THREAD

**Issue by kishori1912** [OfficeDev/Office-Add-in-samples#243]
I want to read web config values through Home.js.

**Comment by AlexJerabek** [comment]
Hi @kishori1912,

Could you please provide some context for your request? Is this in reference to a specific Office Add-in sample?

Thanks!

**Comment by kishori1912** [comment]
Hi @AlexJerabek

I created a web excel add-in in a visual studio project. It provides the default web.config file and js, html.
So, I want to access web.config appsetting key value. I tried different things as follows.

<script>
    var varName = '@System.Configuration.ConfigurationManager.AppSettings["Text"]';
</script>

It did not work for me because it required an MVC view page. 
Can I get any reference or guidance on how I can access appsetting value in excel web add-in?

**Comment by AlexJerabek** [comment]
Thank you @kishori1912. @davidchesnut, could you please take a look?

**Comment by davidchesnut** [comment]
Hi @kishori1912,

You could pass the information from the controller to the view using ViewData. Such as in this [walkthrough](https://www.c-sharpcorner.com/article/asp-net-mvc-passing-data-from-controller-to-view/)  Or you can set up a model with the data, and [reference that model from the view](https://stackoverflow.com/questions/16688099/how-to-use-model-data-in-a-view-asp-mvc). 

Just be careful as these approaches send the data down with the view to the client browser where it can get cached or potentially accessed by malicious code. So don't send any secrets or access tokens down the client with this approach.

Hope this helps,
David
