### ISSUE TITLE
how to make excel custom function work?

### ISSUE THREAD

**Issue by oldoldman** [OfficeDev/Office-Add-in-samples#245]
**Question**

I'm trying to reproduce the excel custom functions ```storage``` on my local machine
1.  configure the manifest file , and put it in a shared folder
2.  copy all files in this [directory](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Excel-custom-functions/Storage/src/functions) to my local http server.
3. in excel add the addin in the shared folder
4. from the local http server log , I can see that excel has retrieved the the following files
 a. functions.html
 b. functions.json
 c. functions.js

In my understanding , up to now , there might be 3 custom functions there , they are : ADD/STOREVALUE/GETVALUE , but I can't find any of them. What I've missed ? Many thanks!

**Comment by AlexJerabek** [comment]
Hi @oldoldman,

Thanks for trying out the sample.  I'm assign @alison-mk to assist. I have a couple questions to help clarify your issue:

1. Did you change the functions' namespace? By default, they start with `CONTOSO` (so, `CONTOSO.ADD`, `CONTOSO.STOREVALUE`, etc.).
2. Have you tried running the sample with the entire codebase? If you copy everything from the [storage folder](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Excel-custom-functions/Storage) and run the add-in, do you see the taskpane? Are the custom functions showing up then? 
3.  Be sure to [clear your cache](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache) if you make changes to the functions or are having issues.

**Comment by oldoldman** [comment]
1. Did you change the functions' namespace? By default, they start with `CONTOSO` (so, `CONTOSO.ADD`, `CONTOSO.STOREVALUE`, etc.).
Yes. I'm using the namespace ```EBI``` in my manifest ```<bt:String id="functions_namespace" DefaultValue="EBI"/>```. I believe it is no a problem
2. Have you tried running the sample with the entire codebase? If you copy everything from the [storage folder](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Excel-custom-functions/Storage) and run the add-in, do you see the taskpane? Are the custom functions showing up then?
I've tried the entire codebase. This time I can see the taskpane when I click the command button and the taskpane works fine (i.e. I can send and receive the token as expected) but the custom functions still does not show.
3. Be sure to [clear your cache](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache) if you make changes to the functions or are having issues.
 Yes. I've tried.

BTW. when opening the taskpane , I got a message : ```the addin only support Microsoft 365 subscriber license, and does not support Office license```, does this matter ? If so , how to change the manifest to support Office license ? Many thanks.

**Comment by oldoldman** [comment]
Hi guys, any suggestion?

**Comment by alison-mk** [comment]
Hi @oldoldman, thank you for the information. It sounds like you have a one-time purchase version of Office, and not a Microsoft 365 subscriber license. Is that accurate? If yes, which one-time purchase version of Office are you using? 

Custom functions will not work on any one-time purchase version of Office prior to Office 2021. See the following article for a list of the platforms that support custom functions: [Office client application and platform availability for Office Add-ins: Custom Functions (Excel only)](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-availability#custom-functions-excel-only). 

You can use this sample with Excel on the web without a Microsoft 365 subscriber license. 

Thanks, 
Alison

**Comment by oldoldman** [comment]
Hi @Alison, it works now. But I'm not sure which one of the following 2 things I'v done in the last day makes it works
1. joined the Microsoft 365 Developer Program , i.e. I have an account on *.onmicrosoft.com
2. update my excel from 16.0.14701.20262 to 16.0.14729.20254. The start screen text changed from Excel 2019 to Microsoft 365.

**Comment by alison-mk** [comment]
Hi @oldoldman, that's great news! I'm glad the sample works for you now. You'd need to complete both steps 1 and 2 for the sample to work. The CustomFunctionsRuntime 1.3 requirement set needs a minimum Office build number of 16.0.13127.20296 for Office on Windows (connected to a Microsoft 365 subscription). See the table on [Custom Functions requirement sets](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/custom-functions-requirement-sets) for more information.

I've added platform availability information to the custom functions samples to help avoid this confusion in the future, and I'll close this issue now that the sample is working for you. 

Cheers, 
Alison
