### ISSUE TITLE
manage filesystem with fs or another api for pc?

### ISSUE THREAD

**Issue by MwSpaceLLC** [OfficeDev/Office-Add-in-samples#257]
> Note: This repo is only for questions related to its samples. If you have questions about how to use office.js or the Office developer platform, please post your question on https://stackoverflow.com. Tag your question with office-js or outlook-web-addins

**Question**

Hi there,

Sorry, we must complete one add-in that search in windows folders. We can't find any API for interact with fs as node.

U have any help for work with filesystem?

Example app => input file folder for search images and put image in excel cel as product ID.
![image](https://user-images.githubusercontent.com/29952045/151607642-0946ef2b-0b50-41b1-91d9-35d0c6196317.png)

Tnks for reply, Alex

**Comment by Rick-Kirkham** [comment]
Office Add-ins are web applications and they restricted in the same ways that any web applications are restricted. By default, web applications cannot interact with the file system on the user's computer except in certain very specific ways. Cookie files can be saved to the file system. But web applications cannot search the file system by default. You might find some workarounds or special libraries if you search the internet for "how can my web app access the file system?". But these techniques may not be supported in all (or maybe not in any) of the embedded webview controls that Office add-ins run in.

**Comment by MwSpaceLLC** [comment]
Thanks @Rick-Kirkham for your quick reply, we have now solved the problem. We are able to upload files normally via browser, but do we have a way to disable this pop-up? 🕵️‍♂️

![image](https://user-images.githubusercontent.com/29952045/151625543-19d1b3ed-8e4c-421d-9a5d-eec2472b58ca.png)

**Comment by Rick-Kirkham** [comment]
I don't read that language. Can you tell me in English what the popup is saying?

**Comment by MwSpaceLLC** [comment]
This Alert is generated from an HTML input file that we are trying to insert to let the user choose the search folder for the photos to insert in the Excel file. When the user clicks on the input file button and chooses the folder this Alert appears, but sometimes it doesn't work. If you press upload instead or if you press cancel, upload the folder once and 3 times. So every now and then it doesn't seem to work. I would like to remove to grant file choice permissions.

Then sorry if it's not the right place Where to ask these questions, I checked online but our team struggles to get this Technical information online, By the way it would be nice to be able to access that Alert to warn the user that there was a sudden error in the program. For example, the algorithm returns error we would like to use that alert that you see in the picture if possible.

![image](https://user-images.githubusercontent.com/29952045/151666837-1c59381d-b639-412c-9993-7139457e028f.png)

**Comment by Rick-Kirkham** [comment]
Where are you uploading the files to?
