### ISSUE TITLE
Addin is installed but command not available

### ISSUE THREAD

**Issue by jbk75** [OfficeDev/Office-Add-in-samples#270]
> Note: This repo is only for questions related to its samples. If you have questions about how to use office.js or the Office developer platform, please post your question on https://stackoverflow.com. Tag your question with office-js or outlook-web-addins

**Question**

Hi,
when I run this in VS everything opens up fine, I see the add-in installed in web outlook, 
but I do not see the AttachmentDemoWeb command in the menu. 
What could be the issue?

Best regards
Jóhann

**Comment by AlexJerabek** [comment]
Hi @jbk75,

I'm sorry you're having issues. Could you please specify which sample is the one you're having problems with?

**Comment by jbk75** [comment]
Hi @AlexJerabek thanks for answering ! :-]
I'm trying to get Samples/auth/Outlook-Add-in-SSO running in my environment.

The status is now : I got this working in the web outlook! but in the Outlook desktop client I get an error:
ADD-IN ERROR.
This add-in could not be started. Close this dialogto ignore the problem or click Restart to try again.

What could be causing this and what is the best way to debug the addin?

Best regards
Jóhann

**Comment by AlexJerabek** [comment]
Thanks @jbk75.

Let me tag @ElizabethSamuel-MSFT to follow-up. In the meantime, could you please provide your version of Outlook? Your version of Outlook might not support the Identity APIs, as specified here: https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets#outlook-client-support

**Comment by jbk75** [comment]
Hey @AlexJerabek, @ElizabethSamuel-MSFT
thanks for the pointers!
I got this working!  The fail was that I was not logged into the correct account in Outlook, silly me :)

Best regards
Jóhann
