### ISSUE TITLE
Error > API is not supported in this platform

### ISSUE THREAD

**Issue by jbk75** [OfficeDev/Office-Add-in-samples#275]
> Note: This repo is only for questions related to its samples. If you have questions about how to use office.js or the Office developer platform, please post your question on https://stackoverflow.com. Tag your question with office-js or outlook-web-addins

**Question**

Hi, 
regarding the Samples/Outlook-Add-in-SSO add-in.

It is working in web Outlook, however in the Outlook desktop client I get following error :
EXCEPTION: {"name":"API Not Supported","message":"API is not supported in this platform.","code":13012}

What could be causing this ?

**Comment by AlexJerabek** [comment]
Hi @jbk75,

That error message indicates that your version of Outlook does not support some feature in the sample. The list of what is supported by the different versions can be found here: https://docs.microsoft.com/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets#outlook-client-support

Please let me know if that information doesn't align with your situation.

**Comment by jbk75** [comment]
Hi @AlexJerabek,
I see it is working to save the attachments, it goes to the diaLogFallback method and the files are saved to the onedrive after I login.  
However I am also trying to create a task in planner using Graph API (from the same outlook addin).  
It is working fine in the web outlook but in the outlook desktop client it just hangs showing the spinning icon.
If I debug this I can see that I get the access token fine but after that I dont know what happens in the code.
Can you give me some tips, how I could possibly debug this and find out what the error could be ?

**Comment by AlexJerabek** [comment]
@ElizabethSamuel-MSFT or @Rick-Kirkham, is there any advice you could provide here?

**Comment by Rick-Kirkham** [comment]
@jbk75 First, it is not clear to me if you are still having the original problem or if you are past that and are now asking about a new problem or if you are describing two different problems. If you are still seeing the 13012 error, see [13012](https://docs.microsoft.com/office/dev/add-ins/develop/troubleshoot-sso-in-office-add-ins#13012).

In general, you debug the server-side code in Visual Studio just like any ASP.NET web app. Just put breakpoints in the C# code. We recently revised our article about debugging client-side code in a Visual Studio add-in project. Please see [Debug Office Add-ins in Visual Studio](https://docs.microsoft.com/office/dev/add-ins/develop/debug-office-add-ins-in-visual-studio).

Please get back to us, if none of this information helps.

**Comment by jbk75** [comment]
Hey @Rick-Kirkham,
thanks for the reply.

Yes I get the 13012 error still.  My Outlook client version is:
Microsoft® Outlook® for Microsoft 365 MSO (Version 2112 Build 16.0.14729.20312) 64-bit 
When will this version be supported so that SSO login will work?

Best regards
Johann

**Comment by Rick-Kirkham** [comment]
@jbk75 Your version of Outlook should support the API. So maybe one of the less common causes of 13012 applies. Is your add-in sending `allowConsentPrompt` as one of the options when it calls `getAccessToken`? As I understand it, there is a bug in Outlook that causes 13012 when you are sideloading the add-in, as you are when you are developing, and you pass that option. If so, try removing that option and see if it fixes the 13012 error. (You can put it back when you go to production. It only happens when sideloading.)

**Comment by jbk75** [comment]
Hi @Rick-Kirkham.
I removed the allowConsentPrompt and send only in the following options:
options = { allowSignInPrompt: true, forMSGraphAccess: true };
But I still get the error :
OSF.DDA.Error {name: "API Not Supported", message: "API is not supported in this platform.", code: 13012}

But if this is only issue when you are developing/debugging then I can live with that.

I'm gonna try to publish the add-in in the cloud admin center and see how it works

**Comment by AlexJerabek** [comment]
Hi @jbk75,

Did this issue with the sample get resolved for you? If so (or I don't hear from you), I'll go ahead and close the issue.
