### ISSUE TITLE
Outlook-Add-in-SSO invalid manifest

### ISSUE THREAD

**Issue by jbk75** [OfficeDev/Office-Add-in-samples#278]
Hi,
Im trying to deploy the manifest in the microsoft 365 admin center.
But I get the error: Manifest file validation has failed.

what could be the issue ?

Best regards 
Jóhann

**Comment by AlexJerabek** [comment]
Hi @jbk75,

Could you please provide a little more context for your issue?

1. Are you deploying the manifest _as-is_ from the sample? Or has it been edited in any way?
2. Have you made other edits to the sample? Or are you testing what happens what the sample is deployed?
3. In the M365 admin center, are you using [integrated apps](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/test-and-deploy-microsoft-365-apps?view=o365-worldwide) or [centralized deployment](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide) to deploy your add-in.
4. What is your M365 environment? Are you using a sandbox from the [developer program](https://developer.microsoft.com/en-us/microsoft-365/dev-program) or your company's subscription?

Thanks!

**Comment by jbk75** [comment]
1. Are you deploying the manifest _as-is_ from the sample? Or has it been edited in any way?
>I made some minor changes to the manifest:
        for example: changed:  id, display name and description
	added values to existing sections like scopes section and Urls
 2. Have you made other edits to the sample? Or are you testing what happens what the sample is deployed?
  > yes, I have added new controller (based on the saveAttachment controller) that talks to the planner in the graph API .
 3. In the M365 admin center, are you using [integrated apps](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/test-and-deploy-microsoft-365-apps?view=o365-worldwide) or [centralized deployment](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide) to deploy your add-in.
>I was using integrated  
4. What is your M365 environment? Are you using a sandbox from the [developer program](https://developer.microsoft.com/en-us/microsoft-365/dev-program) or your company's subscription?
> I have a test m365 environment set up here at my work.

**Comment by AlexJerabek** [comment]
Thanks for the information @jbk75.

@davidchesnut, could you please take a look?

**Comment by davidchesnut** [comment]
Hi @jbk75,

Sorry for the late follow up to this issue. I set this sample up as an integrated app in my test m365 environment and it is working correctly. Just to check a few things.

- Are you loading the manifest from the `\Office-Add-in-samples\Samples\auth\Outlook-Add-in-SSO\AttachmentDemo\bin\Debug\OfficeAppManifests` folder? You want to be sure to use the one VS builds, and not the parent one that has placeholders.
- Did you update the ID placeholder in the ` <WebApplicationInfo>` section at the bottom of the manifest with the ID from your app registration?

If you are still having the issue, can you provide a version of a manifest that we can use to repo the problem? Can just post it to GitHub if you want. 

Thanks!
David
