### ISSUE TITLE
DefaultMinVersion="1.10" for outlook-set-signature

### ISSUE THREAD

**Issue by maxCSA** [OfficeDev/Office-Add-in-samples#293]
**Describe the bug**

[outlook-set-signature] sample use the signature API which is available from version 1.10, so manifest should reflect that.

**To Reproduce**

The Add-ins isn't compatible with version prior to 1.10

**Expected behavior**

Add-ins shouldn't be load if version 1.10 is not available

**Environment**
Example : Outlook 2016 shouldn't load the Add-ins

**Additional context**

https://docs.microsoft.com/en-us/javascript/api/requirement-sets/outlook/requirement-set-1.10/outlook-requirement-set-1.10?view=common-js-preview

**Comment by AlexJerabek** [comment]
Thanks for reporting this issue @maxCSA.

@samantharamon, could you plese investigate?

**Comment by samantharamon** [comment]
Hi @maxCSA,

Thank you again for catching this. The change is pending review in [PR #299](https://github.com/OfficeDev/Office-Add-in-samples/pull/299). Should you have additional feedback, please do not hesitate to let us know.
