### ISSUE TITLE
Why do we need to enable implicit flow for the app?

### ISSUE THREAD

**Issue by kapilash** [OfficeDev/Office-Add-in-samples#306]
> Note: This repo is only for questions related to its samples. If you have questions about how to use office.js or the Office developer platform, please post your question on https://stackoverflow.com. Tag your question with office-js or outlook-web-addins

**Question**

The [instructions for app registration](https://github.com/OfficeDev/Office-Add-in-samples/blob/main/Samples/auth/Outlook-Add-in-SSO/README.md#register-the-add-in-with-azure-ad-v20-endpoint) are suggesting that we create an implicit grant flow (Point 6).

1. But the code does not seem to rely anywhere [on implicit flow](https://github.com/OfficeDev/Office-Add-in-samples/blob/39a7105582287bc82ffde7844167d53381a1867b/Samples/auth/Outlook-Add-in-SSO/AttachmentDemoWeb/Controllers/AzureADAuthController.cs#L46-L53)
 
2. There are suggestions that [implicit grant flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow#prefer-the-auth-code-flow) is no longer suitable.

Can you please help us understand if the implicit flow is mandatory or recommended for addins?

**Comment by ElizabethSamuel-MSFT** [comment]
@kapilash Thanks for your question.

@davidchesnut Can you take a look?

Thanks.

**Comment by davidchesnut** [comment]
Thanks @kapilash! I'll look into this sample.

**Comment by Rick-Kirkham** [comment]
FWIW, the code comment "Gets IdToken from implicit flow and sends it to main add-in window." does not accurately describe the method it is on. That method is using the AuthCode flow.

**Comment by davidchesnut** [comment]
Thanks @Rick-Kirkham, I'm adding a link here to the code comment so I don't forget to update it: https://github.com/OfficeDev/Office-Add-in-samples/blob/39a7105582287bc82ffde7844167d53381a1867b/Samples/auth/Outlook-Add-in-SSO/AttachmentDemoWeb/Controllers/AzureADAuthController.cs#L46

**Comment by kapilash** [comment]
thanks @davidchesnut!
