### ISSUE TITLE
Contextual tabs for Content App addins in Excel

### ISSUE THREAD

**Issue by ksdaniel** [OfficeDev/Office-Add-in-samples#308]
**Is your feature request related to a problem? Please describe.**

It's not really a bug - it's more of an inconsistency. 

**Describe the solution you'd like**

There was some investment and improvements in the contextual tabs API, that makes it possible to create some neatly integrated experiences.  

The problem is that it makes use of the shared javascript runtime. 

This cannot be configured for Content Apps (xsi:type="ContentApp") - at least according to current documentation. 

Can we get an example on how this could be achieved?

**Describe alternatives you've considered**

We could try to somehow repackage the whole addin as a taskpane app, with an invisible taskpane. But that's a really nasty hack.

**Comment by Rick-Kirkham** [comment]
@ksdaniel You are correct that contextual tabs is not supported for Content add-ins. In fact, no type of ribbon / menu customization is possible with content add-ins. Conceptually, Content add-ins are not intended to add to the functionality of the Office application. Instead, they are intended to surface web-based content in Office documents. I'm not clear on what your scenario is, but if you are thinking that you need ribbon customization, then you must adding functionality to the Office application, so you probably don't want a Content add-in anyway. BTW, I believe that you can have an add-in of `xsi:type="TaskPaneApp"` without having any button whose `<Action>` type is `ShowTaskpane`. In other words, you just have one or more buttons whose type is `ExecuteFunction`. Moreover, you could have only _contextual_ tabs. 

I'll leave this issue open for a while in case you have additional questions.
