### ISSUE TITLE
Problem with SSO

### ISSUE THREAD

**Issue by lory0221** [OfficeDev/Office-Add-in-samples#316]
> Note: This repo is only for questions related to its samples. If you have questions about how to use office.js or the Office developer platform, please post your question on https://stackoverflow.com. Tag your question with office-js or outlook-web-addins

**Question**

_Ask your question here._

Hi, I implemented the plug in and I changed the endpoint not to be onedrive, but the sso doesn't work anymore, suggestions?

**Comment by davidchesnut** [comment]
Hi @lory0221,

Can you give us some more details about the changes, and the error you are seeing? Is this on Office on Windows, web, or Mac? Which endpoint did you change to?

My immediate guess would just be to be sure you updated the app registration so it has the correct scopes for the new endpoint. Also you need to update the scopes in code and the manifest to match.

Cheers,
David

**Comment by lory0221** [comment]
Hi @davidchesnut 
I have the problem on the browser (edge or chrome) of a windows machine. 
I have to contact a web service with an authorized token, and at the moment i'm using this scopes: 
        <Scopes>
          <Scope>openid</Scope>
          <Scope>profile</Scope>
          <Scope>offline_access</Scope>
          <Scope>files.readwrite</Scope>
          <Scope>mail.read</Scope>
			
        </Scopes>

And every time the app go in fallback and ask the credentials

**Comment by davidchesnut** [comment]
Hi @lory0221,

Okay if it goes to the fallback code, that most likely means the call to getAccessToken() is returning an error. I'd put a breakpoint there and get the text of the error. 

When you say you need to contact a web server, are you referring to mail or file services in Microsoft Graph? That's what the current scopes indicate. Also the files.readwrite scope is for OneDrive (initially you indicated that you changed the endpoint to NOT be OneDrive. So if there is a mismatch between the manifest list of scopes, and the API permissions from Graph requested in your Azure app registration that will cause getAccessToken to fail.

BTW: Which sample did you start with?

Thanks!
David

**Comment by davidchesnut** [comment]
I think the bot saw this tagged as a programming question and closed it. But please comment if you still need any help here.
