### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by ryanj11** [OfficeDev/Office-Add-in-samples#339]
Apologies if this shouldn't be logged under Bugs. Feel free to delete.

On this page - https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/hello-world/outlook-hello-world - there is a link to https://github.com/OfficeDev/Office-Add-in-samples/blob/main/Samples/hello-world/outlook-hello-world/run-the-sample-on-outlook-on-windows which returns a 404. The link text is "Run the sample on Outlook on Windows".

Is it possible for this to be fixed? Would anyone have a link to moved article if it exists?

**Comment by AlexJerabek** [comment]
Thanks for reporting this @ryanj11. I've created PR #340 to fix that link.
