### ISSUE TITLE
Word Add-in Context Menu Function Issue

### ISSUE THREAD

**Issue by vivek-lakhataria** [OfficeDev/Office-Add-in-samples#346]
I have created Word Add-in using your example, 
Add in loads successfully contextMenu is loading successfully,
but when i click on the context menu button it is not interacting with TaskPane UI,

Here is my Code ####
Function.js File >>
Office.onReady(() => {});

(function () {
    Office.initialize = function () { };
})();

function callThisFunction(event) {
    wordRunFunction();
    event.completed();
}

Office.actions.associate("callThisFunction", callThisFunction);

=========================================================
Home.Js File >>

function wordRunFunction() {
    Word.run(async (context) => {

        const selectionIS = context.document.getSelection();
        selectionIS.load('text');
        selectionIS.load();
        await context.sync();
        var textValue = selectionIS.text;
        const paragraph = context.document.body.insertParagraph(
            "ExecuteFunction works : " + textValue, Word.InsertLocation.end
        );

        paragraph.font.color = "blue";
        await context.sync();    
  
        $('#printcard').append(textValue);
    });
}

======================================================

Hoping you can Help

**Comment by AlexJerabek** [comment]
Thanks for reporting this @vivek-lakhataria.

@ElizabethSamuel-MSFT, could you please take a look?

**Comment by ElizabethSamuel-MSFT** [comment]
@vivek-lakhataria Can you also share a version of your manifest? Did you start off with the Hello World example (https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/hello-world/word-hello-world)?

Also, can you provide some details about your environment?
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______

As much information as you can provide should be helpful.

Thanks.

**Comment by vivek-lakhataria** [comment]
Yes I started with Hello World example.
Platform - Visual Studio 2022 word add in 
Host - Word
Office Version Number - 1.1
Operating System - Windows 10

**Comment by vivek-lakhataria** [comment]
Manifest
========================================================================

<?xml version="1.0" encoding="UTF-8"?>

<OfficeApp
          xmlns="http://schemas.microsoft.com/office/appforoffice/1.1"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0"
          xmlns:ov="http://schemas.microsoft.com/office/taskpaneappversionoverrides"
          xsi:type="TaskPaneApp">

	

	
	<Id>f2566041-f2ca-42bc-8c02-c74ef2ea23e8</Id>

	
	<Version>1.0.0.0</Version>
	<ProviderName>[Provider name]</ProviderName>
	<DefaultLocale>en-US</DefaultLocale>
	
	<DisplayName DefaultValue="dsfdsfsdsf" />
	<Description DefaultValue="dsfdsfsdsf"/>
	
	<IconUrl DefaultValue="~remoteAppUrl/Images/Button32x32.png" />

	<SupportUrl DefaultValue="http://www.contoso.com" />
	
	<AppDomains>
		<AppDomain>AppDomain1</AppDomain>
		<AppDomain>AppDomain2</AppDomain>
		<AppDomain>AppDomain3</AppDomain>
	</AppDomains>
	

	
	<Hosts>
		<Host Name="Document" />
	</Hosts>
	<DefaultSettings>
		<SourceLocation DefaultValue="~remoteAppUrl/Home.html" />
	</DefaultSettings>
	

	<Permissions>ReadWriteDocument</Permissions>

	
	<VersionOverrides xmlns="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="VersionOverridesV1_0">

		
		<Hosts>
			
			
			
			<Host xsi:type="Document">
				
				<DesktopFormFactor>
					
					<GetStarted>
						
						<Title resid="Contoso.GetStarted.Title"/>

						
						<Description resid="Contoso.GetStarted.Description"/>

						
						<LearnMoreUrl resid="Contoso.GetStarted.LearnMoreUrl"/>
					</GetStarted>
					
					<FunctionFile resid="Contoso.DesktopFunctionFile.Url" />

					
					<ExtensionPoint xsi:type="PrimaryCommandSurface">
						
						<OfficeTab id="TabHome">
							
							<Group id="Contoso.Group1">
								
								<Label resid="Contoso.Group1Label" />
								
								
								<Icon>
									<bt:Image size="16" resid="Contoso.tpicon_16x16" /> 
									<bt:Image size="32" resid="Contoso.tpicon_32x32" />
									<bt:Image size="80" resid="Contoso.tpicon_80x80" />
								</Icon>

								
								<Control xsi:type="Button" id="Contoso.TaskpaneButton">
									<Label resid="Contoso.TaskpaneButton.Label" />
									<Supertip>
										
										<Title resid="Contoso.TaskpaneButton.Label" />
										
										<Description resid="Contoso.TaskpaneButton.Tooltip" />
									</Supertip>
									<Icon>
										<bt:Image size="16" resid="Contoso.tpicon_16x16" />
										<bt:Image size="32" resid="Contoso.tpicon_32x32" />
										<bt:Image size="80" resid="Contoso.tpicon_80x80" />
									</Icon>

									
									<Action xsi:type="ShowTaskpane">
										<TaskpaneId>ButtonId1</TaskpaneId>
										
										<SourceLocation resid="Contoso.Taskpane.Url" />
									</Action>
								</Control>								
							</Group>
						</OfficeTab>
					</ExtensionPoint>
					<ExtensionPoint xsi:type="ContextMenu">
						<OfficeMenu id="ContextMenuText">
							<Control xsi:type="Menu" id="TestMenu2">
								<Label resid="ContextMenu.Label" />
								<Supertip>
									<Title resid="ContextMenu.Label" />
									<Description resid="TaskpaneButton.Tooltip" />
								</Supertip>
								<Icon>
									<bt:Image size="16" resid="Contoso.tpicon_16x16" />
									<bt:Image size="32" resid="Contoso.tpicon_32x32" />
									<bt:Image size="80" resid="Contoso.tpicon_80x80" />
								</Icon>
								<Items>
									<Item id="showGallery2">
										<Label resid="ContextMenu.Label"/>
										<Supertip>
											<Title resid="ContextMenu.Label" />
											<Description resid="TaskpaneButton.Tooltip" />
										</Supertip>
										<Icon>
											<bt:Image size="16" resid="Contoso.tpicon_16x16" />
											<bt:Image size="32" resid="Contoso.tpicon_32x32" />
											<bt:Image size="80" resid="Contoso.tpicon_80x80" />
										</Icon>
										<Action xsi:type="ShowTaskpane">
											<TaskpaneId>ButtonId1</TaskpaneId>
											<SourceLocation resid="Contoso.Taskpane.Url" />
										</Action>
									</Item>
									<Item id="showGallery3">
										<Label resid="ContextMenu.Label2"/>
										<Supertip>
											<Title resid="ContextMenu.Label2" />
											<Description resid="TaskpaneButton.Tooltip" />
										</Supertip>
										<Icon>
											<bt:Image size="16" resid="Contoso.tpicon_16x16" />
											<bt:Image size="32" resid="Contoso.tpicon_32x32" />
											<bt:Image size="80" resid="Contoso.tpicon_80x80" />
										</Icon>
										<Action xsi:type="ExecuteFunction">
											<FunctionName>getSelection</FunctionName>
										</Action>
									</Item>
								</Items>
							</Control>
						</OfficeMenu>
					</ExtensionPoint>
				</DesktopFormFactor>
			</Host>
		</Hosts>

		
		<Resources>
			<bt:Images>
				<bt:Image id="Contoso.tpicon_16x16" DefaultValue="~remoteAppUrl/Images/Button16x16.png" />
				<bt:Image id="Contoso.tpicon_32x32" DefaultValue="~remoteAppUrl/Images/Button32x32.png" />
				<bt:Image id="Contoso.tpicon_80x80" DefaultValue="~remoteAppUrl/Images/Button80x80.png" />
			</bt:Images>
			<bt:Urls>
				<bt:Url id="Contoso.DesktopFunctionFile.Url" DefaultValue="~remoteAppUrl/Functions/FunctionFile.html" />
				<bt:Url id="Contoso.Taskpane.Url" DefaultValue="~remoteAppUrl/Home.html" />
				<bt:Url id="Contoso.GetStarted.LearnMoreUrl" DefaultValue="https://go.microsoft.com/fwlink/?LinkId=276812" />
			</bt:Urls>
			
			<bt:ShortStrings>
				<bt:String id="residLabel" DefaultValue="GetData">
					<bt:Override Locale="ja-jp" Value="JA-JP-GetData" />
				</bt:String>
				<bt:String id="ContextMenu.Label" DefaultValue="Context menu..."/>
				<bt:String id="ContextMenu.Label2" DefaultValue="Click Me."/>
				<bt:String id="Contoso.TaskpaneButton.Label" DefaultValue="Show Taskpane" />
				<bt:String id="Contoso.Group1Label" DefaultValue="Commands Group" />
				<bt:String id="Contoso.GetStarted.Title" DefaultValue="Get started with your sample add-in!" />
			</bt:ShortStrings>
			
			<bt:LongStrings>
				<bt:String id="TaskpaneButton.Tooltip" DefaultValue="Click to Show a Taskpane"/>
				<bt:String id="residToolTip" DefaultValue="Get data for your document.">
					<bt:Override Locale="ja-jp" Value="JA-JP - Get data for your document." />
				</bt:String>
				<bt:String id="Contoso.TaskpaneButton.Tooltip" DefaultValue="Click to Show a Taskpane" />
				<bt:String id="Contoso.GetStarted.Description" DefaultValue="Your sample add-in loaded succesfully. Go to the HOME tab and click the 'Show Taskpane' button to get started." />
			</bt:LongStrings>
		</Resources>
	</VersionOverrides>
	

</OfficeApp>

**Comment by ElizabethSamuel-MSFT** [comment]
@vivek-lakhataria Thanks for providing this information. However, can you let us know which version of Office you're using (e.g., Office 2019)? Do have a Microsoft 365 subscription? Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@vivek-lakhataria Seems like you may have started off with the [Word quick start that's based on Visual Studio](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=visualstudio) instead of the hello-word sample? Can you confirm? Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@vivek-lakhataria When you say "when i click on the context menu button it is not interacting with TaskPane UI", what do you mean?

![image](https://user-images.githubusercontent.com/28541963/178072454-e04e7f1b-aeb6-4766-ae03-a23ba85189b9.png)

When I open the context menu, hover over **Context menu...**, then click the **Context menu...** in the submenu, the task pane opens. What is the behavior you're expecting and what's the behavior you're seeing?
