### ISSUE TITLE
Creating docker solution for Office Add-Ins

### ISSUE THREAD

**Issue by praveenbattula** [OfficeDev/Office-Add-in-samples#348]
Hello, I have a requirement to create docker for add-ins. I have created React app, and added docker file to my project. When I am trying to create docker, in build process I see all looking good. But, docker run fails. 
Below is my package.json file: 

{
  "name": "office-addin-taskpane-react",
  "version": "0.0.1",
  "repository": {
    "type": "git",
    "url": "https://github.com/OfficeDev/Office-Addin-TaskPane-React.git"
  },
  "license": "MIT",
  "config": {
    "app_to_debug": "word",
    "app_type_to_debug": "desktop",
    "dev_server_port": 3000
  },
  "scripts": {
    "build": "webpack --mode production",
    "build:dev": "webpack --mode development",
    "dev-server": "webpack serve --mode development",
    "lint": "office-addin-lint check",
    "lint:fix": "office-addin-lint fix",
    "prettier": "office-addin-lint prettier",
    "start": "office-addin-debugging start manifest.xml",
    "start:desktop": "office-addin-debugging start manifest.xml desktop",
    "start:web": "office-addin-debugging start manifest.xml web",
    "stop": "office-addin-debugging stop manifest.xml",
    "validate": "office-addin-manifest validate manifest.xml",
    "watch": "webpack --mode development --watch"
  },
  "homepage": ".",
  "dependencies": {
    "@fluentui/react": "^8.52.3",
    "core-js": "^3.9.1",
    "es6-promise": "^4.2.8",
    "jquery": "^3.6.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "regenerator-runtime": "^0.13.7"
  },
  "devDependencies": {
    "@babel/core": "^7.13.10",
    "@babel/preset-typescript": "^7.13.0",
    "@types/dotenv-webpack": "^7.0.3",
    "@types/jquery": "^3.5.14",
    "@types/office-js-preview": "^1.0.315",
    "@types/office-runtime": "^1.0.17",
    "@types/react": "^17.0.39",
    "@types/react-dom": "^17.0.11",
    "@types/react-hot-loader": "^4.1.1",
    "@types/webpack": "^4.4.34",
    "@types/webpack-dev-server": "^4.1.0",
    "acorn": "^8.5.0",
    "babel-loader": "^8.2.2",
    "copy-webpack-plugin": "^9.0.1",
    "css-loader": "^6.7.1",
    "dotenv-webpack": "^7.1.1",
    "eslint": "^7.20.0",
    "eslint-plugin-office-addins": "^2.0.0",
    "eslint-plugin-react": "^7.28.0",
    "file-loader": "^6.2.0",
    "html-loader": "^2.1.2",
    "html-webpack-plugin": "^5.3.2",
    "less": "^3.9.0",
    "less-loader": "^10.0.1",
    "office-addin-cli": "^1.3.5",
    "office-addin-debugging": "^4.3.8",
    "office-addin-dev-certs": "^1.7.7",
    "office-addin-lint": "^2.0.0",
    "office-addin-manifest": "^1.7.7",
    "office-addin-prettier-config": "^1.1.4",
    "os-browserify": "^0.3.0",
    "process": "^0.11.10",
    "source-map-loader": "^3.0.0",
    "style-loader": "^3.3.1",
    "ts-loader": "^9.2.5",
    "typescript": "^4.3.5",
    "typescript-plugin-css-modules": "^3.4.0",
    "webpack": "^5.50.0",
    "webpack-cli": "^4.8.0",
    "webpack-dev-server": "4.7.3"
  },
  "prettier": "office-addin-prettier-config",
  "browserslist": [
    "ie 11"
  ]
}

And below is **dockerfile**. 

FROM node:14.9.0
LABEL version="1.0"
LABEL description="This is the base docker image for the Office Add-In"
WORKDIR /src
ENV debug_level=debug
COPY ["package.json", "package-lock.json", "./"]
RUN npm install
COPY . .
EXPOSE 3000
CMD ["npm", "start"]

docker run command is giving me below errors (I hope all dependencies installed successfully):
`
Error: Cannot find module 'ajv/dist/core'
Require stack:
- /src/node_modules/ajv-draft-04/dist/index.js
- /src/node_modules/@microsoft/teams-manifest/build/index.js
- /src/node_modules/office-addin-manifest/lib/export.js
- /src/node_modules/office-addin-manifest/lib/main.js
- /src/node_modules/office-addin-dev-settings/lib/appcontainer.js
- /src/node_modules/office-addin-dev-settings/lib/main.js
- /src/node_modules/office-addin-debugging/lib/commands.js
- /src/node_modules/office-addin-debugging/lib/cli.js
- /src/node_modules/office-addin-debugging/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:742:27)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at Module.patchedRequire [as require] (/src/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/src/node_modules/ajv-draft-04/dist/index.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/src/node_modules/ajv-draft-04/dist/index.js',
    '/src/node_modules/@microsoft/teams-manifest/build/index.js',
    '/src/node_modules/office-addin-manifest/lib/export.js',
    '/src/node_modules/office-addin-manifest/lib/main.js',
    '/src/node_modules/office-addin-dev-settings/lib/appcontainer.js',
    '/src/node_modules/office-addin-dev-settings/lib/main.js',
    '/src/node_modules/office-addin-debugging/lib/commands.js',
    '/src/node_modules/office-addin-debugging/lib/cli.js',
    '/src/node_modules/office-addin-debugging/cli.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! office-addin-taskpane-react@0.0.1 start: `office-addin-debugging start manifest.xml`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the office-addin-taskpane-react@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-07-07T20_09_29_244Z-debug.log`
thanks for the help!

**Comment by davidchesnut** [comment]
Hi @praveenbattula,

Have you checked that ajv/dist/core does exist as expected? Also be sure you are running the container in a Windows environment (not Linux) as the office-addin-debugging module expects Windows. Or you need to remove that module and just run Node JS server directly for Linux.

If you are still stuck can you please post the question on stackoverflow [office-js] [outlook-web-addins]? Your description and detail in the question is perfect!
