### ISSUE TITLE
Excel on Windows?

### ISSUE THREAD

**Issue by jemery27** [OfficeDev/Office-Add-in-samples#359]
The samples say they should work on Windows and Mac as well as O365. Are there any notes how to do that - like import in visual studio code and run in excel on windows? I can run them in O365 and even run the local web server etc, but not understanding how to run in local Excel application. I have built my own addins using VSC and npm build / start etc, but these samples seem to need something else to make them work. Appreciate any tips.

Thanks,
Jason

**Comment by Rick-Kirkham** [comment]
I'm not clear on what you are asking. Is there a sample that is not working? If so, could you specify which one? Are you trying to test in on Windows or on Mac or on the web?

**Comment by jemery27** [comment]
The specific sample I was testing was "excel-shared-runtime-scenario". I
was able to make it work using the info in the readme in office 365 on the
web. However, downloading the sample and opening it in visual studio code
then building it with "npm run build" fails. I'd like to work and develop
on local Excel on windows and trying to use some of the concepts in my own
addon. I know it's probably not the sample itself that is the problem but
wondering if there were any instructions to get the samples working in
Excel in windows for example.

Thanks,
Jason

**Comment by davidchesnut** [comment]
Hi @jemery27,

This sample doesn't use a web framework. It's just a collection of static HTML pages and resources. So there isn't anything to "build". If your goal is to have a project that you can start building on, you'll need to use the following steps.

1. Run "yo office" and generate the template that you want (React, Office host, etc...)
2. Modify the generated project to use the [shared runtime following these steps](https://docs.microsoft.com/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime).
3. Copy the code you need from this sample into the new project.

Hope this helps,
David

**Comment by jemery27** [comment]
Ok yeah I thought it needed to build to register the functions in Excel. I
don;t particularly care if there is a framework, static HTML would be fine,
I guess I;m not quite understanding what is required to run this code in
the windows excel app - do I have to install the framework or can I run it
as static html?

Thanks again,
Jason

**Comment by jemery27** [comment]
I guess another way to ask this might be - could anyone outline some steps
to replicate this sample even to develop against in O365? All my past
experience was with VBA and with the code loading from github I am not sure
how I can create my own 'instance' to work off of or what needs to change
to make that work. Seemed like downloading the code and working in visual
studio code would be a good option, but that didn't seem to work.

Thanks again,
Jason

**Comment by davidchesnut** [comment]
Hi Jason,
You can start with this sample. You'll just be coding in plain HTML/JS, which is completely fine. Office Add-ins do not require a framework. It's just as you get to larger, complex add-ins a framework makes it much easier to deal with JS file dependencies or updating the HTML DOM on the fly.

1. So you can use Visual Studio Code to make changes to the sample.
2. Then [start the localhost web server for your code](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/excel-shared-runtime-scenario#run-the-sample-from-localhost)
3. Then [sideload the manifest-localhost.xml file to Excel on Windows](https://docs.microsoft.com/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins)

Office Add-ins are very different than working in VBA or VSTO. The shared runtime scenario sample contains multiple features which makes it kind of complex to start with. I recommend taking a look at the [Excel Hello World sample](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/hello-world/excel-hello-world). It's the least amount of code you can write to get an add-in started, but it shows the fundamental parts of the add-in (manifest, initialization...) for getting started.

Cheers,
David

**Comment by davidchesnut** [comment]
Will go ahead and close this issue, but please reopen if you still have any issues with the sample. Thanks!
