### ISSUE TITLE
Can't find  /src/commands/ribbonJSON.js file

### ISSUE THREAD

**Issue by minyu007** [OfficeDev/Office-Add-in-samples#365]
> Note: This repo is only for questions related to its samples. If you have questions about how to use office.js or the Office developer platform, please post your question on https://stackoverflow.com. Tag your question with office-js or outlook-web-addins

**Question**

_Ask your question here._

Can't find  /src/commands/ribbonJSON.js file

**Comment by davidchesnut** [comment]
Hi @minyu007 are you looking for this file? https://github.com/OfficeDev/Office-Add-in-samples/blob/main/Samples/office-contextual-tabs/src/commands/ribbonJSON.js

Or are you looking at a different sample?

Thanks!
David
