### ISSUE TITLE
Custom function batching pattern benefits

### ISSUE THREAD

**Issue by sboudouk** [OfficeDev/Office-Add-in-samples#372]
**Question**

Hello, 

First of all thanks for you work and your commitment. 

I am actually building an add-in that call multiple endpoint of my API, so I naturally decide to check the `Custom function batching pattern` that you guys provided in the samples.

The sample looks accurate enough, code wise, but actually It does not really explain what are the benefits of this, performance wise. 

Will your batch custom functions reload be faster this way ? By reading the samples docs it is not clear enough  to me if it's something related to good practices , a performance tip, or both.

Can you please provide more explanation on this ? 

Once again thanks for your work & time.

**Comment by AlexJerabek** [comment]
Hi @sboudouk,

Thank you for the question. I'll assign @alison-mk to investigate and answer.

**Comment by sboudouk** [comment]
Hello @alison-mk , any news here ? Thanks.

**Comment by alison-mk** [comment]
Hi @sboudouk, 

The primary benefits of following a batching pattern for your custom functions add-in are related to network performance, and not performance of Excel the application.

The main benefits of following a batching pattern are:
- Each call to a remote web service takes time. Each call must be sent (requested) and then a response returned, and there is often a delay between requests and responses. Batching the calls means they are all sent at once, and then the responses returned at once, reducing the overall request/response processing time.
- A remote web service may have limits in how many network calls it accepts, and batching calls helps avoid encountering a limit.

I've updated the README.md file of the *Custom function batching pattern* add-in to clarify this benefit. This issue will close when that PR is merged. 

Thanks, 
Alison

**Comment by sboudouk** [comment]
Thanks for the answer & the action, crystal clear.
