### ISSUE TITLE
Custom Excel remote request batching fusing input paramter (range)

### ISSUE THREAD

**Issue by geoHeil** [OfficeDev/Office-Add-in-samples#415]
The excel javascript API can request data from an external service as outlined here: https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-web-reqs

https://github.com/OfficeDev/Office-Add-in-samples/blob/main/Excel-custom-functions/Batching/src/functions/functions.js#L96 is a great example for batching.

However, imagine a UDF that must retrieve contiguous parts of a database or API. Each cell would need to call out to the server repeatedly and a lot of unnecessary requests and latency pile up.

Is it possible to batch up these requests, i.e. 

- 1) detect the start/end of the range
- 2) fetch the data in a single request
- 3) update the range in Excel asynchronously (to not block the UI)

**Comment by AlexJerabek** [comment]
Hi @geoHeil,

Thanks for the question. Getting large amounts of data to apply across a range sounds like the job of a [taskpane-based add-in](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator), instead of a Custom Function. There's a series of articles about working with ranges, including this one on [setting range values](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-ranges-set-get-values). You can have your add-in batch the updates as you wish, use the [`load`/`sync` pattern in the Excel-specific APIs](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/application-specific-api-model).

Please let me know if this information is helpful, or if there's a compelling reason to use custom functions for this scenario. Thanks!

**Comment by geoHeil** [comment]
Der @AlexJerabek , 

similar to what Bloomberg is showing here https://youtu.be/FwN7lZPbYXE?t=2826 I want to have the data accessible via the UDF. Indeed, batching is possible - but not solving my issue. In fact, the client (before batching) would need to perform operator fusion (i.e. detect that subsequent calls to the UDF) are in fact not (random) point lookups but rather a range scan in a database.

Do you @AlexJerabek  see any efficient way how to handle the UDF-based data access pattern?

**Comment by AlexJerabek** [comment]
Hi @geoHeil,
Let me tag @yaweizhu-henson from the product team to help look at your scenario and understand if there is a better approach.

**Comment by geoHeil** [comment]
@yaweizhu-henson do you have any updates?

**Comment by yaweizhu-henson** [comment]
Sorry for  late response. I just see the email notification today. I will involve our engineer in this to see if your requirement can be supported today.
@JHJ-MS

**Comment by geoHeil** [comment]
@yaweizhu-henson @JHJ-MS any updates on this? Can you explain to what extent this feature is or will be supported?

**Comment by JHJ-MS** [comment]
Hi @geoHeil, sorry for the late response. 
A Custom Function can return an array of results showing in neighboring cells.([The doc for your reference](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-dynamic-arrays)).  Could you take a look at it to see whether it can achieve your scenario?  You can fetch the data in a single request in one Custom Function, deal with the data within the Function, then return an array of results.

**Comment by geoHeil** [comment]
I think this is not what I need. As you are talking about the return path of the data (where your suggested approach would work fine). I am interested in the query path: and there this batching would not work well (as far as I understand).

The current batching approach only allows to reduce the number of requests but is not fusing the requests i.e. 
- select * from mydb where key = row1
- select * from mydb where key = row2
- select * from mydb where key = row3

Could be run then and evaluated at once (3 calls to the SQL) in the DB and returned in a single request.

What I am asking for is that for contiguous ranges (scans) I would like to be able to fuse these individual row-based (UDF) requests for data to a single call to the API (i.e. select * from mydb where key in (row1, row2, row3) or i.e. a date range and then return the data.

Your suggestion is covering the last part where the data could be spilled to the neighbors. But not the first one around fusion (not to be confused with batching).

**Comment by jakobpn** [comment]
@geoHeil I would suggest that you take a look at this sample https://learn.microsoft.com/en-us/samples/officedev/pnp-officeaddins/excel-custom-function-batching-pattern/

**Comment by geoHeil** [comment]
Exactly. I think I even linked this pattern at the start of this thread:
> The excel javascript API can request data from an external service as outlined here: https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-web-reqs
>
> https://github.com/OfficeDev/Office-Add-in-samples/blob/main/Excel-custom-functions/Batching/src/functions/functions.js#L96 is a great example for batching.

But this is not what I want. I want operator fusion i.e. fuse the separate rows (of the UDF) into one contiguous range / select statement from the data source and then later spill the array to each of the input rows.

So far I do not see a way to perform this with the current batching API. Am I overlooking any point?

**Comment by geoHeil** [comment]
As far as I understand the current batching API is only suitable for reducing unnecessary network calls. Instead of calling the remote service once for each row/cell, it is called for batches (every 10th or 100th row). Each batch is computed (item by item in the batch) but then returned as a list (batch) i.e. single network request. In any case, there is a 1:1 reference of the cell and its result.

What I am thinking about is the fusion of the operators not batching i.e.:
- detection of a contiguous range and pushdown as a single query (not batch of multiple queries) to the data store.
- spilling the result to all the involved cells. 

So far, in particular, the 2nd step is unclear to me, as the reference to the cells which need to be updated would most likely be lost when fusing their operators (i.e. there is no longer a 1:1 relationship.

**Comment by jakobpn** [comment]
geoHeil, I am available to connect with you on a Teams call so we can discuss how you could solve for this. Let me know, if this is something you want to do.

**Comment by geoHeil** [comment]
Great! How would next week on Tuesday or perhaps even better Wednesday work for you? I will send you an e-mail.

**Comment by geoHeil** [comment]
Thank you for the great explanation on the call. Let me close this issue here.
