### ISSUE TITLE
Smart alerts not working on New Mac UI with manifest

### ISSUE THREAD

**Issue by mkondadg** [OfficeDev/Office-Add-in-samples#416]
Testing below manifest file on Windows / Mac 

https://github.com/OfficeDev/Office-Add-in-samples/blob/main/Samples/outlook-check-item-categories/manifest.xml

As per documentation, (https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough?tabs=xmlmanifest#differences-between-smart-alerts-and-the-on-send-feature), Smart Alerts is supported on New Mac UI.
But the above manifest is documented to work only in Windows, when would this work on New Mac UI or if supported, is there a way to customize the manifest to work on Mac ?

Tested on :

Windows Outlook version : Version 2209 Build 16.0.15629.20200) 64-bit 
Mac New UI version : 16.61 (22050700)

**Comment by AlexJerabek** [comment]
Thanks for the question @mkondadg.

@samantharamon, can you please confirm the accuracy of the Mac support and the timeline?

**Comment by mkondadg** [comment]
Any update @samantharamon ?

**Comment by samantharamon** [comment]
Hi @mkondadg,

Apologies for the delayed response. I've verified that Smart Alerts is supported on the new Mac UI starting in Version 16.65.827.0. When you get a chance, could you please update your Outlook on Mac client and try the sample again? Let me know if that resolves the issue.

**Comment by mkondadg** [comment]
Hi @samantharamon 
I tested the same after upgrading to 16.66.2 Mac new UI on BigSur
The manifest file used is https://github.com/OfficeDev/Office-Add-in-samples/blob/main/Samples/outlook-check-item-categories/manifest-localhost.xml

The same addin is deployed on windows and gives smart alert as below.

![windows smart alerts - send appointment - alert2](https://user-images.githubusercontent.com/62250655/199364379-f4909dd1-b460-4018-ada7-0d75fda26c3b.png)

But on Mac the same addin doesnt give any error.
Do you want me to collect diagnostic logs ?

**Comment by samantharamon** [comment]
Thanks for testing that and providing additional details, @mkondadg. Let me test this further this week to see if I can replicate the issue. Are you able to run the add-in created from the [Smart Alerts walkthrough](https://learn.microsoft.com/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough?tabs=xmlmanifest) on a Mac by any chance?

**Comment by mkondadg** [comment]
A bit progress but not completely working.

Used below manifest file with most of the data from https://learn.microsoft.com/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough?tabs=xmlmanifest

[smartalerts-mac-manifest.xml.zip](https://github.com/OfficeDev/Office-Add-in-samples/files/9923386/smartalerts-mac-manifest.xml.zip)

Smart Alert seen
![macnewui - smart alerts2](https://user-images.githubusercontent.com/62250655/199579622-80f0f90b-2db2-44f2-80b9-c6affe81abe7.png)

But mail not sent after clicking on "Send Anyway"
![macnewui - smart alerts1](https://user-images.githubusercontent.com/62250655/199579591-14577434-5456-4165-a198-8ea9906aebdb.png)

**Comment by samantharamon** [comment]
Thanks for sharing the manifest you're using, @mkondadg. I'll test this further and get back to you.

**Comment by samantharamon** [comment]
Thank you again for providing your test results, @mkondadg. I'm able to replicate the issue you're experiencing. I'll be working with the team to troubleshoot the sample on a Mac further. I forgot to request this in an earlier post. When you get a chance, may I request for your diagnostic logs?

I created an add-in from scratch using the [Smart Alerts walkthrough](https://learn.microsoft.com/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough?tabs=xmlmanifest) and verified that it runs as expected on the Mac platform (this is without incorporating the GitHub sample aspects). If you'd like to test the Smart Alerts feature while we look into the GitHub sample further, I recommend completing the walkthrough and customizing your add-in from there. Apologies for the inconvenience.

**Comment by mkondadg** [comment]
@samantharamon could you provide the manifest xml generated using https://learn.microsoft.com/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough?tabs=xmlmanifest ?

Could you let me know how to generate the diagnostic logs for this case which will be useful to you ?

**Comment by samantharamon** [comment]
We use the add-in project created from the [Outlook quick start](https://learn.microsoft.com/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator) as a basis (see the ['Set up your environment'](https://learn.microsoft.com/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough?tabs=xmlmanifest#set-up-your-environment) section of the walkthrough), then replace the \<VersionOverrides\> element in the manifest with the one in the walkthrough. This is the manifest used: [manifest.zip](https://github.com/OfficeDev/Office-Add-in-samples/files/9964857/manifest.zip). Let me know if that works for you.

To enable and generate logs, please refer to [Runtime logging on Mac](https://learn.microsoft.com/office/dev/add-ins/testing/runtime-logging#runtime-logging-on-mac). Once you have logging set up, please run the GitHub sample add-in, then attach the .txt file to this post. Thanks!

**Comment by mkondadg** [comment]
@samantharamon Unable to reproduce the sendmail issue even with the same manifest xml I provided earlier. I tried redeploying multiple times and even restarted the machine and disabled runtime logging as well.
The outlook app version is still the same.
Could you try testing in your previously reproducible setup ?

I deployed the manifest you provided and it works as expected.

![SmartAlerts-sample-working1](https://user-images.githubusercontent.com/62250655/200699483-43877bcf-ae19-4e7d-a66b-adea78d06269.png)

![SmartAlerts-sample-working2](https://user-images.githubusercontent.com/62250655/200699495-704a364b-8cda-4dfa-9b14-4508384923e6.png)

![SmartAlerts-sample-working3](https://user-images.githubusercontent.com/62250655/200699511-1965ae59-01e9-4ca4-98e9-7ebae4543247.png)

**Comment by samantharamon** [comment]
Thank you for the update, @mkondadg. I'm glad to hear you were able to create an add-in using the walkthrough. I tested configuring the sample's SendMode attribute to PromptUser and I'm also now able to send the email after selecting the Send Anyway option. However, I still receive the "add-in is unavailable" dialog. If possible, could you still provide the logs you get from running the sample?

**Comment by mkondadg** [comment]
@samantharamon Sorry for the delay.

Using the earlier manifest from sample (which was blocking sending anyway earlier, now sends the mail)
[22_smartalerts_partialworking_backup.xml.zip](https://github.com/OfficeDev/Office-Add-in-samples/files/10014247/22_smartalerts_partialworking_backup.xml.zip)

Enabled this log setting
defaults write com.microsoft.Outlook CEFRuntimeLoggingFile -string "runtime_logs3.txt"
Here is the log
[runtime_logs3.txt](https://github.com/OfficeDev/Office-Add-in-samples/files/10014250/runtime_logs3.txt)

**Comment by samantharamon** [comment]
No worries, @mkondadg. Thank you for including the manifest and logs.

**Comment by samantharamon** [comment]
Thanks for your patience, @mkondadg. We've updated the [sample](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/outlook-check-item-categories) to now support the Outlook on Mac client. When you get a chance, please try sideloading the sample's manifest.xml file and let me know if you're able to run it successfully.

**Comment by mkondadg** [comment]
@samantharamon thanks for the update.
Let me try the latest one and get back to you.
