### ISSUE TITLE
 Office-Add-in-NodeJS-SSO deployed in appservice not working (production scenario)

### ISSUE THREAD

**Issue by anantharengan** [OfficeDev/Office-Add-in-samples#440]
We created a powerpoint web addin node sso based on the below articles
https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Office-Add-in-NodeJS-SSO 
https://learn.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs

It works fine on localhost. (ran project from command prompt -> npm start to run the project)

So for production we created an app service and deployed the same powerpoint addin which works well in localhost by following the comments mentioned in the below article
https://github.com/OfficeDev/Office-Add-in-NodeJS-SSO/issues/61#issuecomment-821517972 

we sideloadeded the addin in powerpoint web and we are getting the below issue and the addin is not working

![image](https://user-images.githubusercontent.com/35441650/205073651-0e310293-8aff-45dd-80d1-ffe6aef7ce16.png)

get 404 when we try to access /home/index ( <SourceLocation DefaultValue="https://{appservice url}/home/index"/>)

![image](https://user-images.githubusercontent.com/35441650/205074671-1cbc7f74-351a-446c-afc9-172fcc0e9723.png)

package.json is like below

{
  "name": "ssoapp",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "install-dev-certs": "office-addin-dev-certs install",
    "start": "node ./bin/www"
  },
  "dependencies": {
    "@types/jquery": "^3.5.5",
    "@types/office-js": "^1.0.264",
    "cookie-parser": "~1.4.5",
    "debug": "~4.3.1",
    "dotenv": "^9.0.2",
    "express": "~4.17.1",
    "form-urlencoded": "^6.0.3",
    "http-errors": "~1.8.0",
    "jquery": "^3.6.0",
    "jshint": "^2.12.0",
    "jsonwebtoken": "^8.5.1",
    "morgan": "~1.10.0",
    "node-fetch": "^2.6.7",
    "pug": "^3.0.2",
    "@azure/msal-node": "1.8.0",
    "jwks-rsa": "^2.0.5",
    "uuid": "^8.3.1"
  },
  "devDependencies": {
    "office-addin-dev-certs": "1.5.18"
  }
}

Can you please help out to fix this issue. Please reach out to me if you need anymore information. Thanks

**Comment by anantharengan** [comment]
@davidchesnut can you please help here.

**Comment by davidchesnut** [comment]
Hi @anantharengan, thanks for letting us know about this issue. I'll take a look. In the meantime, if you are seeing a 404, you might check to be sure the Node.js server successfully started without any errors on the server after deployment.

**Comment by anantharengan** [comment]
> Hi @anantharengan, thanks for letting us know about this issue. I'll take a look. In the meantime, if you are seeing a 404, you might check to be sure the Node.js server successfully started without any errors on the server after deployment.

Thanks @davidchesnut  for the quick response. Please find the details below

My powerpoint addin structure deployed in app service is shown below

structure (1/2)
![image](https://user-images.githubusercontent.com/35441650/205113906-5c0099f6-eed4-43d9-b539-c1ea109909ec.png)

structure (2/2)
![image](https://user-images.githubusercontent.com/35441650/205114027-7afb2261-9017-4edc-a9a7-f7a408f60d67.png)

my configuration entries in app service (note : added port no as 443 (highlighted in yellow below))

![image](https://user-images.githubusercontent.com/35441650/205114613-79d2509c-9efb-4461-a965-101f85a2475d.png)
 
and finally when i run **'node www'** from bin folder (ran directly from kudu tools in app service)
![image](https://user-images.githubusercontent.com/35441650/205115064-8f17e4f5-0845-4f39-af74-cdfde1548dad.png)


Is there any other way to check to make sure Node.js server is successfully started without any errors on the server after deployment. If so kindly share it.

Kindly help us resolve this issue.

**Comment by davidchesnut** [comment]
It looks like it doesn't like something in the www file at the indicated line numbers. Did you update the www file to remove office-addin-dev-certs and use server certs?

**Comment by anantharengan** [comment]
> It looks like it doesn't like something in the www file at the indicated line numbers. Did you update the www file to remove office-addin-dev-certs and use server certs?

Thanks @davidchesnut  for the reply. I saw the www file code seems good to me. sharing the entire www file contents below kindly go through it and provide your suggestions. Thanks in advance



#!/usr/bin/env node

/**
 * Module dependencies.
 */

var app = require('../app');
var debug = require('debug')('ssoapp:server');
var devCerts = require('office-addin-dev-certs');
var https = require('https');
var fs = require('fs');


/**
 * Get port from environment and store in Express.
 */


var port = normalizePort(process.env.PORT || '44355');


app.set('port', port);

/**
 * Create HTTP server.
 */
startServer(app, port);

/**
 * Normalize a port into a number, string, or false.
 */

function normalizePort(val) {
  var port = parseInt(val, 10);

  if (isNaN(port)) {
    // named pipe
    return val;
  }

  if (port >= 0) {
    // port number
    return port;
  }

  return false;
}

/**
 * Event listener for HTTP server "error" event.
 */

function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  var bind = typeof port === 'string'
    ? 'Pipe ' + port
    : 'Port ' + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
}

async function startServer(app, port) {
  if (process.env.NODE_ENV === 'development') {
    const options = await devCerts.getHttpsServerOptions();
    https.createServer(options, app).listen(port, () => console.log(`Server running on ${port}`));
  }
  else {    
    app.listen(process.env.port || 1337, () => console.log(`Server listening on port  ${port}`));
  }
}

**Comment by davidchesnut** [comment]
Yep, you definitely want to remove the office-addin-dev-certs package from this file. It won't work. I think Azure generates certs for your deployment that you want to use instead.

**Comment by anantharengan** [comment]
> Yep, you definitely want to remove the office-addin-dev-certs package from this file. It won't work. I think Azure generates certs for your deployment that you want to use instead.

Hi @davidchesnut thanks for the reply. As per the below piece of code

async function startServer(app, port) {
if (process.env.NODE_ENV === 'development') {
const options = await devCerts.getHttpsServerOptions();
https.createServer(options, app).listen(port, () => console.log(Server running on ${port}));
}
else {
**app.listen(process.env.port || 1337, () => console.log(Server listening on port ${port}));**
}
}

The line highlighted in bold in above code will only execute when the environment is **'production'** .  So we are not using any office-addin-dev-certs package when the environment is 'production'. 

FYI. We are authenticating using client id and client secret by following the below article 
https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Office-Add-in-NodeJS-SSO
https://learn.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs 

In your reply you have mentioned like **'I think Azure generates certs for your deployment that you want to use instead.'** i do not understand what you mean by that. Can you please elaborate more on this.? 

Thanks

**Comment by anantharengan** [comment]
@davidchesnut Can you please help out here

**Comment by anantharengan** [comment]
> > Yep, you definitely want to remove the office-addin-dev-certs package from this file. It won't work. I think Azure generates certs for your deployment that you want to use instead.
> 
> Hi @davidchesnut thanks for the reply. As per the below piece of code
> 
> async function startServer(app, port) { if (process.env.NODE_ENV === 'development') { const options = await devCerts.getHttpsServerOptions(); https.createServer(options, app).listen(port, () => console.log(Server running on ${port})); } else { **app.listen(process.env.port || 1337, () => console.log(Server listening on port ${port}));** } }
> 
> The line highlighted in bold in above code will only execute when the environment is **'production'** . So we are not using any office-addin-dev-certs package when the environment is 'production'.
> 
> FYI. We are authenticating using client id and client secret by following the below article https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Office-Add-in-NodeJS-SSO https://learn.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs
> 
> In your reply you have mentioned like **'I think Azure generates certs for your deployment that you want to use instead.'** i do not understand what you mean by that. Can you please elaborate more on this.?
> 
> Thanks

@davidchesnut can you please help

**Comment by davidchesnut** [comment]
Doesn't the `require('office-addin-dev-certs')` pull in the code from office-addin-dev-certs? The package code is built to run in a Windows or Mac environment, so I don't know if it will actually load correctly. Although I have not tested that specific scenario.

I checked the www file that I used, and I commented out that `require` line. Otherwise looks the same as yours.

Sorry I was referring to the SSL certificate, not the client secret. I think that's automatically configured when you create the app service.

**Comment by anantharengan** [comment]
> Doesn't the `require('office-addin-dev-certs')` pull in the code from office-addin-dev-certs? The package code is built to run in a Windows or Mac environment, so I don't know if it will actually load correctly. Although I have not tested that specific scenario.
> 
> I checked the www file that I used, and I commented out that `require` line. Otherwise looks the same as yours.
> 
> Sorry I was referring to the SSL certificate, not the client secret. I think that's automatically configured when you create the app service.

Hi @davidchesnut thanks for the reply. I have removed `require('office-addin-dev-certs')` and also commented the lines using them. Still get the same issue (tested in kudu for the app service). 

![image](https://user-images.githubusercontent.com/35441650/205501508-15df266e-46d5-4e62-8e52-6d9d05a0b107.png)
 
Can there be any other reason for this or can i share  the codebase for you to check out. Kindly help.

**Comment by anantharengan** [comment]
> > Doesn't the `require('office-addin-dev-certs')` pull in the code from office-addin-dev-certs? The package code is built to run in a Windows or Mac environment, so I don't know if it will actually load correctly. Although I have not tested that specific scenario.
> > I checked the www file that I used, and I commented out that `require` line. Otherwise looks the same as yours.
> > Sorry I was referring to the SSL certificate, not the client secret. I think that's automatically configured when you create the app service.
> 
> Hi @davidchesnut thanks for the reply. I have removed `require('office-addin-dev-certs')` and also commented the lines using them. Still get the same issue (tested in kudu for the app service).
> 
> ![image](https://user-images.githubusercontent.com/35441650/205501508-15df266e-46d5-4e62-8e52-6d9d05a0b107.png)
> 
> Since the app is listening to port no : 443. Do we need to configure anything in app service or azure add app for it to work.
> 
> Can there be any other reason for this?. Kindly help.

@davidchesnut Can you please share your suggestion or help for this.

**Comment by davidchesnut** [comment]
Hi @anantharengan,

I'm setting up a test so that I can compare and contrast your project with something that I know works.  I took the [Node JS SSO sample](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Office-Add-in-NodeJS-SSO/Complete) and configured an app registration. Then deployed it using VS Code to an Azure app service. This is working and these are the settings I used (just to see if we are working with the same configuration.

app service config:
- Node 16 LTS
- Windows deployment (I see you are using this already)

VS Code project change:
- I moved all folders and files under a 'public' folder, then configured the public folder to deploy. Updated the settings.json file in .vscode folder to include `"appService.deploySubpath": "public"`.

On the app service, I added the following app settings (no longer using the .ENV right now):
- `SCM_DO_BUILD_DURING_DEPLOYMENT` = true
- `CLIENT_ID` = _yourclientid_
- `CLIENT_SECRET`= _yourclientsecret_
- `DIRECTORY_ID` = _yourdirectoryid_

Now when I deploy, it automatically runs npm install, builds, and starts the server. No need to attempt from the console.

Finally I generated a new www file (as I was having some issues different from yours) and used the following. This may work for you:

```javascript
#!/usr/bin/env node

/**
 * Module dependencies.
 */

var app = require('../app');
//var debug = require('debug')('myexpressapp:server');
var http = require('http');

/**
 * Get port from environment and store in Express.
 */

var port = normalizePort(process.env.PORT || '3000');
app.set('port', port);

/**
 * Create HTTP server.
 */

var server = http.createServer(app);

/**
 * Listen on provided port, on all network interfaces.
 */

server.listen(port);
server.on('error', onError);
server.on('listening', onListening);

/**
 * Normalize a port into a number, string, or false.
 */

function normalizePort(val) {
  var port = parseInt(val, 10);

  if (isNaN(port)) {
    // named pipe
    return val;
  }

  if (port >= 0) {
    // port number
    return port;
  }

  return false;
}

/**
 * Event listener for HTTP server "error" event.
 */

function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  var bind = typeof port === 'string'
    ? 'Pipe ' + port
    : 'Port ' + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
}

/**
 * Event listener for HTTP server "listening" event.
 */

function onListening() {
  var addr = server.address();
  var bind = typeof addr === 'string'
    ? 'pipe ' + addr
    : 'port ' + addr.port;
  //debug('Listening on ' + bind);
  console.log('Listening on ' + bind);
}
```

Finally, when you deploy you can stream the logs using the info in [this article](https://learn.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=windows&pivots=development-environment-vscode#stream-logs). This will inform if there are any errors in the install and build during deployment.

Let me know if this helps. Thanks!

**Comment by anantharengan** [comment]
> Hi @anantharengan,
> 
> I'm setting up a test so that I can compare and contrast your project with something that I know works. I took the [Node JS SSO sample](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Office-Add-in-NodeJS-SSO/Complete) and configured an app registration. Then deployed it using VS Code to an Azure app service. This is working and these are the settings I used (just to see if we are working with the same configuration.
> 
> app service config:
> 
> * Node 16 LTS
> * Windows deployment (I see you are using this already)
> 
> VS Code project change:
> 
> * I moved all folders and files under a 'public' folder, then configured the public folder to deploy. Updated the settings.json file in .vscode folder to include `"appService.deploySubpath": "public"`.
> 
> On the app service, I added the following app settings (no longer using the .ENV right now):
> 
> * `SCM_DO_BUILD_DURING_DEPLOYMENT` = true
> * `CLIENT_ID` = _yourclientid_
> * `CLIENT_SECRET`= _yourclientsecret_
> * `DIRECTORY_ID` = _yourdirectoryid_
> * `SERVER_SOURCE` = _your Azure app service URL_
> 
> Now when I deploy, it automatically runs npm install, builds, and starts the server. No need to attempt from the console.
> 
> Finally I generated a new www file (as I was having some issues different from yours) and used the following. This may work for you:
> 
> ```js
> #!/usr/bin/env node
> 
> /**
>  * Module dependencies.
>  */
> 
> var app = require('../app');
> //var debug = require('debug')('myexpressapp:server');
> var http = require('http');
> 
> /**
>  * Get port from environment and store in Express.
>  */
> 
> var port = normalizePort(process.env.PORT || '3000');
> app.set('port', port);
> 
> /**
>  * Create HTTP server.
>  */
> 
> var server = http.createServer(app);
> 
> /**
>  * Listen on provided port, on all network interfaces.
>  */
> 
> server.listen(port);
> server.on('error', onError);
> server.on('listening', onListening);
> 
> /**
>  * Normalize a port into a number, string, or false.
>  */
> 
> function normalizePort(val) {
>   var port = parseInt(val, 10);
> 
>   if (isNaN(port)) {
>     // named pipe
>     return val;
>   }
> 
>   if (port >= 0) {
>     // port number
>     return port;
>   }
> 
>   return false;
> }
> 
> /**
>  * Event listener for HTTP server "error" event.
>  */
> 
> function onError(error) {
>   if (error.syscall !== 'listen') {
>     throw error;
>   }
> 
>   var bind = typeof port === 'string'
>     ? 'Pipe ' + port
>     : 'Port ' + port;
> 
>   // handle specific listen errors with friendly messages
>   switch (error.code) {
>     case 'EACCES':
>       console.error(bind + ' requires elevated privileges');
>       process.exit(1);
>       break;
>     case 'EADDRINUSE':
>       console.error(bind + ' is already in use');
>       process.exit(1);
>       break;
>     default:
>       throw error;
>   }
> }
> 
> /**
>  * Event listener for HTTP server "listening" event.
>  */
> 
> function onListening() {
>   var addr = server.address();
>   var bind = typeof addr === 'string'
>     ? 'pipe ' + addr
>     : 'port ' + addr.port;
>   //debug('Listening on ' + bind);
>   console.log('Listening on ' + bind);
> }
> ```
> 
> Finally, when you deploy you can stream the logs using the info in [this article](https://learn.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=windows&pivots=development-environment-vscode#stream-logs). This will inform if there are any errors in the install and build during deployment.
> 
> Let me know if this helps. Thanks!

Thanks @davidchesnut for the detailed reply i followed all the things as mentioned. But still getting the same error on the logs (i enabled it by having iisnode.yml). Please find the screenshots below

![image](https://user-images.githubusercontent.com/35441650/206510607-4021afdd-a9b7-4ca7-91d3-da00446b7b94.png)

and screenshot one of the entry

![image](https://user-images.githubusercontent.com/35441650/206510738-22bb4614-9d74-4e95-8675-3fc7e76d6a19.png)

It is still throwing permission issue. Do we need to enable reverse proxies for port 443 or anything on those lines. Can you please help.

**Comment by anantharengan** [comment]
> > Hi @anantharengan,
> > I'm setting up a test so that I can compare and contrast your project with something that I know works. I took the [Node JS SSO sample](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Office-Add-in-NodeJS-SSO/Complete) and configured an app registration. Then deployed it using VS Code to an Azure app service. This is working and these are the settings I used (just to see if we are working with the same configuration.
> > app service config:
> > 
> > * Node 16 LTS
> > * Windows deployment (I see you are using this already)
> > 
> > VS Code project change:
> > 
> > * I moved all folders and files under a 'public' folder, then configured the public folder to deploy. Updated the settings.json file in .vscode folder to include `"appService.deploySubpath": "public"`.
> > 
> > On the app service, I added the following app settings (no longer using the .ENV right now):
> > 
> > * `SCM_DO_BUILD_DURING_DEPLOYMENT` = true
> > * `CLIENT_ID` = _yourclientid_
> > * `CLIENT_SECRET`= _yourclientsecret_
> > * `DIRECTORY_ID` = _yourdirectoryid_
> > * `SERVER_SOURCE` = _your Azure app service URL_
> > 
> > Now when I deploy, it automatically runs npm install, builds, and starts the server. No need to attempt from the console.
> > Finally I generated a new www file (as I was having some issues different from yours) and used the following. This may work for you:
> > ```js
> > #!/usr/bin/env node
> > 
> > /**
> >  * Module dependencies.
> >  */
> > 
> > var app = require('../app');
> > //var debug = require('debug')('myexpressapp:server');
> > var http = require('http');
> > 
> > /**
> >  * Get port from environment and store in Express.
> >  */
> > 
> > var port = normalizePort(process.env.PORT || '3000');
> > app.set('port', port);
> > 
> > /**
> >  * Create HTTP server.
> >  */
> > 
> > var server = http.createServer(app);
> > 
> > /**
> >  * Listen on provided port, on all network interfaces.
> >  */
> > 
> > server.listen(port);
> > server.on('error', onError);
> > server.on('listening', onListening);
> > 
> > /**
> >  * Normalize a port into a number, string, or false.
> >  */
> > 
> > function normalizePort(val) {
> >   var port = parseInt(val, 10);
> > 
> >   if (isNaN(port)) {
> >     // named pipe
> >     return val;
> >   }
> > 
> >   if (port >= 0) {
> >     // port number
> >     return port;
> >   }
> > 
> >   return false;
> > }
> > 
> > /**
> >  * Event listener for HTTP server "error" event.
> >  */
> > 
> > function onError(error) {
> >   if (error.syscall !== 'listen') {
> >     throw error;
> >   }
> > 
> >   var bind = typeof port === 'string'
> >     ? 'Pipe ' + port
> >     : 'Port ' + port;
> > 
> >   // handle specific listen errors with friendly messages
> >   switch (error.code) {
> >     case 'EACCES':
> >       console.error(bind + ' requires elevated privileges');
> >       process.exit(1);
> >       break;
> >     case 'EADDRINUSE':
> >       console.error(bind + ' is already in use');
> >       process.exit(1);
> >       break;
> >     default:
> >       throw error;
> >   }
> > }
> > 
> > /**
> >  * Event listener for HTTP server "listening" event.
> >  */
> > 
> > function onListening() {
> >   var addr = server.address();
> >   var bind = typeof addr === 'string'
> >     ? 'pipe ' + addr
> >     : 'port ' + addr.port;
> >   //debug('Listening on ' + bind);
> >   console.log('Listening on ' + bind);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Finally, when you deploy you can stream the logs using the info in [this article](https://learn.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=windows&pivots=development-environment-vscode#stream-logs). This will inform if there are any errors in the install and build during deployment.
> > Let me know if this helps. Thanks!
> 
> Thanks @davidchesnut for the detailed reply i followed all the things as mentioned. But still getting the same error on the logs (i enabled it by having iisnode.yml). Please find the screenshots below
> 
> ![image](https://user-images.githubusercontent.com/35441650/206510607-4021afdd-a9b7-4ca7-91d3-da00446b7b94.png)
> 
> and screenshot one of the entry
> 
> ![image](https://user-images.githubusercontent.com/35441650/206510738-22bb4614-9d74-4e95-8675-3fc7e76d6a19.png)
> 
> It is still throwing permission issue. Do we need to enable reverse proxies for port 443 or anything on those lines. Can you please help.

hi @davidchesnut can you please help on this

**Comment by davidchesnut** [comment]
My guess is there really is some permission problem, but I'm not exactly sure how to debug to isolate that. I'm checking with some folks on the Azure side.

**Comment by davidchesnut** [comment]
Hi @anantharengan,

Doing some more testing I actually reproduced this error. I found that port 443 and 8080 are reserved by the Azure app service. You can't use them in your project. Instead you need to be sure to use 'process.env.PORT' which Azure will pass to your project. the 443 port gets mapped to your project through process.env.PORT. 

Be sure you aren't specifically setting the port to 443 anywhere in your code. Maybe do a global search. Also make sure you didn't specify a port variable in the configuration settings, or the .ENV file. 

Cheers,
David

**Comment by anantharengan** [comment]
> Hi @anantharengan,
> 
> Doing some more testing I actually reproduced this error. I found that port 443 and 8080 are reserved by the Azure app service. You can't use them in your project. Instead you need to be sure to use 'process.env.PORT' which Azure will pass to your project. the 443 port gets mapped to your project through process.env.PORT.
> 
> Be sure you aren't specifically setting the port to 443 anywhere in your code. Maybe do a global search. Also make sure you didn't specify a port variable in the configuration settings, or the .ENV file.
> 
> Cheers, David

Thanks David will check your suggestion and try it out and update you soon
