### ISSUE TITLE
excel-blazor-add-in -- Add-in cannot launch in debugging (F5) when Visual Studio is elevated

### ISSUE THREAD

**Issue by cmeyertons** [OfficeDev/Office-Add-in-samples#443]
**URL of sample**

[excel-blazor-add-in](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/blazor-add-in/excel-blazor-add-in)

**Describe the bug**
Initially described in https://github.com/OfficeDev/Office-Add-in-samples/issues/439.  

When Visual Studio is elevated, the sample does not load the add-in with the following message:

```
The add-in could not be started. Please restart all Office applications and try again
```

When using Ctrl + F5 (Start w/o Debugging), the add-in is able to load successfully.

**To Reproduce**

1. F5 Launch add-in while Visual Studio is being run as administrator

**Expected behavior**

The add-in loading should not fail if running VS in admin.
**Environment**
- Platform : PC Desktop
- Host : Excel
- Office version number: Version 2202 Build 16.0.14931.20806 64 bit
- Operating System: Windows 10 Enterprise 21H2 (confirmed w/ Webview2)

**Comment by Rick-Kirkham** [comment]
This is probably expected behavior determined by the OS or by Visual Studio; not something that can be fixed by changing the sample. So, I'm inclined to think that the only solution is to have the Readme specify that Visual Studio should not be opened elevated. Does that seem right?

**Comment by cmeyertons** [comment]
You are correct that this seems like a bug with the Office Tools for Visual Studio -- is there somewhere we can direct this issue so that it gets routed to the appropriate team?

**Comment by Rick-Kirkham** [comment]
I have updated the Readme with a parenthetical warning. I'm trying to track down where I can file a bug internally.

**Comment by Rick-Kirkham** [comment]
@cmeyertons Here's how to get a bug created and assigned to the correct team: In Visual Studio, navigate to **Help** > **Report a Problem within Visual Studio**, and the issue will be routed to the right owner based on the workload (Office Tools for VS).
