### ISSUE TITLE
excel-blazor-add-in - Breakpoints are not hit from Excel

### ISSUE THREAD

**Issue by cmeyertons** [OfficeDev/Office-Add-in-samples#444]
**URL of sample**

[excel-blazor-add-in](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/blazor-add-in/excel-blazor-add-in)

**Describe the bug**
When debugging the Blazor WASM Excel add-in, no breakpoints are hit in any of the razor files.  

In the same session, if debugging via browser, breakpoints are properly hit.

1. F5 Launch add-in while Visual Studio
2. Set breakpoints in BubbleChart.razor.cs
3. Navigate to BubbleChart via add-in
4. Observe breakpoints aren't loaded and no breakpoints are hit

**Expected behavior**
Breakpoints should be hit and debuggable w/ the sample out of the box.
**Environment**
- Platform : PC Desktop
- Host : Excel
- Office version number: Version 2202 Build 16.0.14931.20806 64 bit
- Operating System: Windows 10 Enterprise 21H2 (confirmed w/ Webview2)

**Comment by Rick-Kirkham** [comment]
This is expected (but regrettable) behavior. The Visual Studio debugger doesn't work with add-ins anymore. To debug with Visual Studio, you need to use the tools associated with the browser. The details are in this article: [Debug Office Add-ins in Visual Studio](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/debug-office-add-ins-in-visual-studio).

**Comment by cmeyertons** [comment]
@Rick-Kirkham is there any guidance for doing so with Blazor?

**Comment by cmeyertons** [comment]
There has to be a way right? If you can remotely debug an add-in in VS code, you should be able to do it with VS because they both use the Chromium remote debugging protocol

**Comment by Rick-Kirkham** [comment]
> @Rick-Kirkham is there any guidance for doing so with Blazor?

I'm not familiar with Blazor. I'll reopen and assign to @davidchesnut who may know.

**Comment by cmeyertons** [comment]
It appears the VS Code add-ins set some registry keys to enable Remote Debugging, but I'm a little lost on how to get Visual Studio to attach to the running tab like VS Code does:
```ps
$addInId = "4aeb7f5e-a283-4a08-83f7-5e7271e4fa2a"
$devPath = "HKCU:\Software\Microsoft\Office\16.0\Wef\Developer"
$regPath = "HKCU:\Software\Microsoft\Office\16.0\Wef\Developer\$addInId"

if (!(Test-Path $regPath)) {
  New-Item -Path $devPath -Name $addInId
}

Set-ItemProperty -Path $regPath -Name "UseDirectDebugger" -Value 1
Set-ItemProperty -Path $regPath -Name "UseLiveReload" -Value 0
Set-ItemProperty -Path $regPath -Name "UseWebDebugger" -Value 0
```

**Comment by AlexJerabek** [comment]
Let me tag @aafvstam to have a look as well.

**Comment by davidchesnut** [comment]
Hi @cmeyertons, I see this behavior as well. Using Visual Studio 2022 I can hit breakpoints in JS, but not the C# code. I'll look into this. @aafvstam do you know of anything that would cause this behavior?
Thanks!

**Comment by aafvstam** [comment]
@davidchesnut I do remember that we briefly discussed this with @danroth27 where the debugger should be redirected to the WebView2 instance in the TaskPane (hosted in the Office Client) instead of the (separately launched) browser. I believe something was done for MAUI as well as MAUI is starting the Blazor WebView (inheriting WebView2?) in the mobile emulator. I guess there is some internal magic included there to make that happen. The other part is how to get the debugger to break on the Blazor/C# code instead of breaking on JS/TS ...

**Comment by aafvstam** [comment]
Update 2:
I did some more testing, and it looks like the cs debugger is actually also attached, but I found that the cs debugger is attached to the browser instance while the js debugger is attached to the TaskPane instance.

If you put in breakpoints in both cs and js on the pages I see it breaking on cs when I hit the buttons in the browser and when I repeat and hit the buttons on the TaskPane the js breakpoints are triggered.

**Comment by cmeyertons** [comment]
@aafvstam is there a way in Visual Studio to attach to the task pane instance correctly as a workaround?

So until the F5 functionality is resolved, a developer can Ctrl + F5 and then attach afterwards if they need to debug?

It appears this is the default flow available for the Office Add-In VS Code experience

**Comment by cmeyertons** [comment]
@aafvstam  i think this is what you were looking for in terms of what MAUI is doing:

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/developer-tools.md

**Comment by danroth27** [comment]
@thaystg might be able to help out here. Or maybe we should get together on a call to go through this scenario? Blazor WebAssembly debugging is a bit complicated and requires correct configuring both the browser and our .NET debug proxy. I'm not sure I understand all the moving parts when debugging an Excel add-in.

**Comment by davidchesnut** [comment]
Hi @cmeyertons,
 
We merged a PR from Thays that adds a fix to this sample (make sure you pick that up in your own project code). However Visual Studio 2022 also needs a fix rolled out before it works. We're targeting VS 17.6 Preview 2 (probably in the next couple of months) for that to roll out and then you should see debugging work.

Cheers,
David
