### ISSUE TITLE
Navigation to other razor component throw an error

### ISSUE THREAD

**Issue by ChhaganSinha** [OfficeDev/Office-Add-in-samples#463]
Hi..
when i am using navigation manager or redirecting, it's throw an error and the application not redirecting to razor component

```
<div class="navbar px-3">
	<div class="container">
		<div class="col-md-2">
			<button @onclick="@(() => MoveToPage("/"))" class="btn btn-primary nav-addin"><div>Attachments</div></button>
		</div>
		<div class="col-md-2">
			<a href="/test" class="btn btn-primary nav-addin"><div>Test</div></a>
		</div>
	</div>
</div>
```

when i click to "Test" it gives following error 

blazor.webassembly.js:1         
     Uncaught TypeError: history.pushState is not a function
    at we (blazor.webassembly.js:1:27710)
    at blazor.webassembly.js:1:19728
    at blazor.webassembly.js:1:13272
    at Array.forEach (<anonymous>)
    at k.onGlobalEvent (blazor.webassembly.js:1:13260)

how i can resolve this problem?
Thanks..

**Comment by erayc-msft** [comment]
Hello - Thanks for your question.  This forum is for issues with our product or documentation and not for programming questions about your code.  For programming questions, you can go to [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/office-js-dev.html) and search or ask questions.  

To better understand the issue - is the error you are reporting specific to the code you added?  
```
	<div class="col-md-2">
		<a href="/test" class="btn btn-primary nav-addin"><div>Test</div></a>
	</div>
```

Do you see errors when you use sample as is or if you use a button?  For example:
```
<div class="col-md-2">
	<button @onclick="@(() => MoveToPage("/test"))" class="btn btn-primary nav-addin"><div>Test</div></button>
</div>
```

Thanks,
Microsoft 365 Developer Platform Team

**Comment by ChhaganSinha** [comment]
Hi....Thanks for response
Actually whenever i am trying to navigate it's giving the error that i have mentioned in my question.

with this 
```
<div class="col-md-2">
	<button @onclick="@(() => MoveToPage("/test"))" class="btn btn-primary nav-addin"><div>Test</div></button>
</div>
```
it's doesn't throw error.

any solution?
