### ISSUE TITLE
Blazor Excel web addin with a custom tab ribbon

### ISSUE THREAD

**Issue by RaoulRSV** [OfficeDev/Office-Add-in-samples#474]
**Question**
My question is about the use a  DotNet.invokeMethodAsync from js to trigger a C# function in a Blazor page using the "call static local method. This is done in a Blazor Excel web addin with a custom tab ribbon . After a click on the proper ribbon button the code stops on the TS callStaticLocalComponentMethod() call,  would its counterpart in C# Blazor component be commented or not. When this callStaticLocalComponentMethod() call is commented the enableButton function works properly and the event is completed.

TS code (App/Button/file.js) : 
```
(window as any).lancerchaîné = async (event) => { 
    await callStaticLocalComponentMethod();   
    enableButtonListe("Nod:false,Yod:true,Sauver:true,Copier:true"); //enables buttons in Ribbon
    event.completed();
};
async function callStaticLocalComponentMethod() {   
    let result = await DotNet.invokeMethodAsync("BlazorAddIn", "LocalStaticMethod");
    alert(result);    
}
`
```
C# code in Blazor component : 
```public partial class Index :IAsyncDisposable
 {
        [Inject]
        public IJSRuntime JSRuntime { get; set; } = default!;
        //public IJSObjectReference JSModule { get; set; } = default!;
        private Lazy<IJSObjectReference> JSModule = new();
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {                
                JSModule = new(await JS.InvokeAsync<IJSObjectReference>("import", "./App/Button/file.js"));
            }
        }      
        public static string LocalStaticMethod() => $"{nameof(LocalStaticMethod)} called";
           
    }
```

Index.html code :

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>Blazor Excel add-in</title>

    <base href="/" />

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="css/app.css" rel="stylesheet" />
    <link href="BlazorAddIn.styles.css" rel="stylesheet" />
    <script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js"></script> 
</head>

<body>
    <!-- The following image URL tracks diagnostic data for this sample add-in. Please remove the image tag if you reuse this sample in your own code project. -->
    <!--<img src="https://pnptelemetry.azurewebsites.net/pnp-officeaddins/samples/blazor-add-in/excel-blazor-add-in-run" />-->

    <div id="app">
        [...]
        </div>
       [...]
    </div>

    <div id="blazor-error-ui">
       [...]
    </div>

    <script src="_framework/blazor.webassembly.js"></script>
    <script src="./App/Button/file.js" type="text/javascript"></script>
      
    });
</body>

</html>
```

  XML code :
`
<bt:Url id="Contoso.SharedRuntime.Url" DefaultValue="~remoteAppUrl/index.html" />
`

Additional information :   `
I am developping a solution combining an Excel web addin project consuming a webapi/Asp.Net core project  (through httppost controller). This solution works satisfactory on localhost but shows speed performance divided by more than 5 when running on the best dedicated Azure servers, most probably because of an higher latence between the 2 projects.

To overcome this issue, my idea is to capitalize on Maarten van Stam sample (https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/blazor-add-in/excel-blazor-add-in) 

starting from that sample, it is quite simple to add a custom tab with buttons add js.file with commands to activate ou desactivate buttons.

Ribbon view : 
![image](https://user-images.githubusercontent.com/54595398/214821497-ba612479-5933-4f8e-88ca-915d306fd102.png)

**Comment by jeremy-msft** [comment]
@davidchesnut and @aafvstam, are you able to help?

**Comment by aafvstam** [comment]
Not sure what the question is ... I guess I need some time to implement what was provided and see what happens here.

@RaoulRSV What exactly are you looking for? The way I read it is that you found an issue but when using the Blazor Sample it is 'solved'.

**Comment by RaoulRSV** [comment]
@aafvstam I am trying to trigger a C# function located in a Blazor page and to get a return from an Excel Ribbon button. I am using your Blazor addin sample. The StaticLocalComponent method used is demonstrated in this [github ](https://github.com/Blazor-School/javascript-interaction-blazor-wasm-dotnet6). The overall idea is to play an Excel Web Addin consuming  an Aspnet Core API in this context in order to get more performance.

**Comment by davidchesnut** [comment]
Hi @RaoulRSV, just to confirm that shared runtime is loading properly for the buttons, do you have this setting in the manifest file.

```xml
<FunctionFile resid="Contoso.SharedRuntime.Url"/>
```

I just want to check that the `resid` matches everywhere it is used in the manifest file, otherwise the shared runtime won't load and I'm pretty sure the Blazor interop would stop working in that scenario.

Thanks!
David

**Comment by aafvstam** [comment]
Did you check in the code on GitHub somewhere to share your code sample with us?
It is a bit tricky to rebuild it from the snippets above without risking running into other errors trying to repro what you did.

**Comment by RaoulRSV** [comment]
@aafvstam  and @davidchesnut 
My code is [here](https://github.com/RaoulRSV/excel-blazor-add-in)
Run it without changing anything, then uncomment FunctionFile.js lig6  (await callStaticLocalComponentMethod();) and re-run it.
You should see a message bottom right of excel sheet such as (your's will be in english)
![Blazor addin blocked](https://user-images.githubusercontent.com/54595398/216038199-f94cead6-4838-4127-ab60-ff2e810088fc.png)
It means that the call to # is blocked.

**Comment by aafvstam** [comment]
So I have been looking at this a bit more in my [livestream](https://twitch.tv/softasinsoftware) and now understasnd a bit better what you were trying to accomplish. I need to do some more research on the exact timing when Blazor and the JS Interop kicks in as I do remember seeing that the JS Interop engine used by Blazor is only available after having been initialized.

It looks like your process is running **before** JS Interop is available and will result in an exception. I want to investigate this to see if there are alternative methods to do what you try to do.

**Comment by RaoulRSV** [comment]
@aafvstam : some further tests. After you launch the project, output logs shows the two messages from BlazorAddin.lib.module.js ("We are now entering function: beforeStart" + "We are now entering function: afterStarted") before any click on the Ribbon button. 
Therefore I don't believe that "my  process is running before JS interop is available" as you stated

**Comment by aafvstam** [comment]
Just wanted to mention I'm still working on this, but it is a tricky mix of technologies to debug properly 😲
Just found that VS 17.6 Preview 2 arrived, this should have a fix on the debugger, which should make things easier to work with.

**Comment by RaoulRSV** [comment]
@aafvstam @davidchesnut 
I did progress somehow on it. Please find [here](https://github.com/RaoulRSV/excel-blazor-add-in-ribbon-JS) an attempt with ribbon. Give a look to output console to see results. The trick was to add some code in BlazorAddin.lib.module.js
 It is partially satisfactory since : 
- you need in the XML a first group of two controls (three doesn't make it): one for the taskframe and the other for a first "executefunction" action. As a consequence you can't avoid the taskframe panel to show after addin opening + an useless button in the ribbon
- it is however possible to add (at least) another group in the XML with "executefunctions"

Please note that if you change anything in the XML you need to reboot your machine and empty wef + browser before relauching the addin in localhost !!!!!!!

Unfortunatly I don't get the same result with typescript, see [here](https://github.com/RaoulRSV/excel-blazor-add-in-ribbon-TS) because Blazor cannot open the index page (see output console. 

Overall my guess is that question is not an pure developer issue and it deserves some additional coding from Blazor teams if they are ever interested  with the huge potential of C#/vbnet developpers willing to publish on appsource.

**Comment by RaoulRSV** [comment]
@aafvstam, @davidchesnut.  Installing VisualStudio 2022 17.6 prev2 seems to solve the main issue : no more need to combine both types of control to get a custom tab button and to change code in BlazorAddIn.lib.module.js to get a regular custom tab button . 

I still have a secondary issue with the TypeScript version of the same project  as shown [here](https://github.com/RaoulRSV/excel-blazor-add-in-TS2). When I run it I get an error in Page.index.ts an error which blocks everything. This error raises an "Uncaught SyntaxError SyntaxError: Invalid or unexpected token"  located in Page.index.ts,  probably due to the  "(window as any).lancerchaine = async (event: Office.AddinCommands.Event) => {" line of code

**Comment by RaoulRSV** [comment]
I propose to close this issue since it is resolved as far as JS is concerned and the TS secondary issue is now transfered to [here](https://github.com/OfficeDev/Office-Add-in-samples/issues/514)
