### ISSUE TITLE
Error CS 5001

### ISSUE THREAD

**Issue by MiftahRizky** [OfficeDev/Office-Add-in-samples#489]
> Note: This template is only for reporting bugs about samples in this repo. If you have a product bug to report about Office web Add-ins, please submit the issue at [https://github.com/OfficeDev/office-js/issues](https://github.com/OfficeDev/office-js/issues/new). This will help us respond to your issue faster.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

**URL of sample**

_URL linking to the sample that has the bug._

**Describe the bug**

_A clear and concise description of what the bug is._

**To Reproduce**

1. _Go to '...'_
2. _Click on '....'_
3. _Scroll down to '....'_
4. _See error_

**Expected behavior**

_A clear and concise description of what you expected to happen. solution "Program does not contain a static "main" method suitable for an entry point"

**Screenshots**

_If applicable, add screenshots to help explain your problem._

**Environment**
- Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
- Host [Excel, Word, PowerPoint, etc.]: Excel
- Office version number: Office 365
- Operating System: Win 10
- Browser (if using Office Online): Chrome

**Additional context**

_Add any other context about the problem here. I Have Problem CS 5001

**Comment by davidchesnut** [comment]
Hi @MiftahRizky, can you include some more details about where you get this error? What sample are you using?

Thanks!
David

**Comment by MiftahRizky** [comment]
can't determine project language from files. please us one of[--csharp,--javascript, typescript, java, phyton, custom]
sample im using is create create worksheet from website

**Comment by davidchesnut** [comment]
Hi @MiftahRizky, That looks like a c# error which would occur in the FunctionCreateSpreadsheet project. It uses c# to create an Azure Function. I think maybe I missed a prerequisite in the readme. Can you check that the Azure Function Core Tools are installed? There's more info at https://learn.microsoft.com/en-us/azure/azure-functions/functions-run-local

If you are still getting the error can you provide a screen shot, or info about when and where you see the error?

Thanks!
David
