### ISSUE TITLE
Stacking Command Buttons Vertically (Word Addin)

### ISSUE THREAD

**Issue by SebastianFKing** [OfficeDev/Office-Add-in-samples#495]
> Note: This repo is only for questions related to its samples. If you have questions about how to use office.js or the Office developer platform, please post your question on https://stackoverflow.com. Tag your question with office-js or outlook-web-addins

**Question**

I am trying to stack command buttons vertically within a group but there does not appear to be any documentation/samples for this in a word addin. Could anyone please assist with this?

**Comment by Rick-Kirkham** [comment]
Please raise this question on https://stackoverflow.com/. Thanks.
