### ISSUE TITLE
.NET7.0 not compatible ascendant with .NET6.0 for BlazorAddin

### ISSUE THREAD

**Issue by RaoulRSV** [OfficeDev/Office-Add-in-samples#512]
**URL of sample**

(https://github.com/RaoulRSV/excel-blazor-add-in-JS-NET6-Ribbon)
Note : the link has been changed 
**Describe the bug**

After updating the sample to .NET 7.0, javascript changes are not reflected in localhost and therefore not included in the run

**To Reproduce**

 - Download sample from github
- In project properties change .NET 6.0 to .NET 7.0. Update Nuget to 7.0.5
- F5 with debugging first time. Check in output console message "initialiser

**Expected behavior**

-  change in Index.js, lig 41  : console.log("initialiser"); to console.log("initialiser2");
- F5 with debugging. Check in output console message  that message is still to"initialiser

**Screenshots**

_If applicable, add screenshots to help explain your problem._

**Environment**
- Platform [PC desktop, Mac, iOS, Office Online]:PC desktop
- Host [Excel, Word, PowerPoint, etc.]:  Excel
- Office version number: N.A.
- Operating System: Windows11
- Browser (if using Office Online):N.A.

**Comment by aafvstam** [comment]
@RaoulRSV Great to have someone deep diving on the Blazor Samples! You keep on bashing with new issues. I'll continue monitoring/working on this as this is my pet-project-sample 😉 will be traveling however upcoming week so expect some delay from my part. Maybe after returning we can hook up in a recurring meeting, I'm extremely interested to see what your use cases are and  see where we can create a better sample covering these scenarios!

**Comment by RaoulRSV** [comment]
@aafvstam. Wait for your call

**Comment by RaoulRSV** [comment]
I did check again  and now the sample works properly for .NET7.0. 
However, it is still raising an error (A process with ID x was not executed) with 8.0 and Github packages with version 3.23177.8

**Comment by RaoulRSV** [comment]
No more error with .Net 8.0 version 5. We can close this issue
