### ISSUE TITLE
Build Solution make disappear ribbon buttons in BlazorAddin

### ISSUE THREAD

**Issue by RaoulRSV** [OfficeDev/Office-Add-in-samples#513]
**URL of sample**

https://github.com/RaoulRSV/excel-blazor-add-in-JS-NET6-Ribbon
Note : the link has been changed

**Describe the bug**

Build Solution makes disappearing custom tab ribbon buttons in BlazorAddin

**To Reproduce**

1. Download sample
2. Run first time and check custom tab buttons on ribbons

**Expected behavior**

3. In Build menu, click on BuildSolution
4. Run a second time, custom tab buttons have disappeared

**Screenshots**

_If applicable, add screenshots to help explain your problem._

**Environment**
- Platform [PC desktop, Mac, iOS, Office Online]: PC desktop,
- Host [Excel, Word, PowerPoint, etc.]: Excel
- Office version number: ______
- Operating System:Windows 11
- Browser (if using Office Online): ______

**Comment by aafvstam** [comment]
@davidchesnut I'll be traveling next week so if you have someone else to look at this, otherwise I'll pick it up the week after.

**Comment by davidchesnut** [comment]
Hi @RaoulRSV,

I see a "No" tab appear on the ribbon with four buttons. This appears even after I rebuild the solution. It appears to work fine on Excel on Windows. Maybe try [clearing the Office cache](https://learn.microsoft.com/office/dev/add-ins/testing/clear-cache) to see if that helps?

Are there any errors that appear in the [runtime log](https://learn.microsoft.com/office/dev/add-ins/testing/runtime-logging)?

Thanks,
David

**Comment by RaoulRSV** [comment]
Hi @davidchesnut 
I did check again and now the sample works properly after rebuild. I have no explaination for it.
 Sorry to have disturbed you

**Comment by yjoshi-msft** [comment]
Closing it based on OPs comment
