### ISSUE TITLE
Deploying event-driven sample to a server

### ISSUE THREAD

**Issue by DylanWilliams1955** [OfficeDev/Office-Add-in-samples#523]
Dear Alex,

I have been working on an event-based Office Add-In that is now working in Outlook on the web with a local host for debugging. However, it fails to work when I try to deploy it to a server.

I am told that the events.html file refered to in the manifest file would usually have a <script> reference in events.html to the associated events.js file with the event handlers. However, the events.html in the sample that I am working from does not have a <script> reference to events.js. Is a <script> reference required in events.html when one deploys to a server?

Also, the events.js uses the require command, as shown below, which seems to be incompatible with a <script> reference in events.html. The first line of the code would not render as written, but starts with three forward slashes and a less-than symbol, and ends with a single forward slash and a greater-than symbol.

`
reference path="../../node_modules/@types/office-js/index.d.ts"
/* global Office require */

const { default: Common } = require("./common");
const { default: SignatureEventWrapper } = require("./signatureEventWrapper");
Office.onReady();
// mount the commands into Office
Office.actions.associate("onMessageSendHandler", (event) => {
  const wrapper = new SignatureEventWrapper();
  wrapper.verifySignature(event);
});
`

Any guidance on how to proceed would be most appreciated! Thank you, Dylan

**Comment by yjoshi-msft** [comment]
Hi Dylan,

Thank you for reaching out. GitHub issues are for reporting potential bugs or errors in our documentation.
I would like to suggest you raise the same clarification on https://stackoverflow.com/questions/tagged/office-js

Hope this helps.
