### ISSUE TITLE
Outlook on Windows - OnAppointmentSend Handler of OfficeJS - not working for API calls 

### ISSUE THREAD

**Issue by satyamkatiyar** [OfficeDev/Office-Add-in-samples#525]
> Note: This repo is only for questions related to its samples. If you have questions about how to use office.js or the Office developer platform, please post your question on https://stackoverflow.com. Tag your question with office-js or outlook-web-addins

**Question**

We are trying make an api call while sending an event using onAppointmentSend Handler, unfortunately its not working in windows.

We tried to follow this link - 
https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough?tabs=xmlmanifest
and this sample code - 
https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/outlook-check-item-categories

**We observed that - if we are including very basic JS code in our file like - localStorage, JSON.Parse or JSON.stringify, Math - it starts failing.**

Below are code snippets - 
![image](https://user-images.githubusercontent.com/26408291/236877827-54f700d8-5394-46c7-8384-1ade539ebbd4.png)
![image](https://user-images.githubusercontent.com/26408291/236878378-0411c42a-0675-4f0f-8c00-2af7f1659e45.png)
![image](https://user-images.githubusercontent.com/26408291/236879374-57c558b8-c029-42e4-81d7-c554d6bb9b87.png)
![image](https://user-images.githubusercontent.com/26408291/236880703-2dee04e8-14a2-4dd0-a9c3-09231f721813.png)

**index.html**
  <script type="text/javascript" src="launchevent.js"></script> 

**launchevent.js**

function onItemSendHandler(event) {
    Office.context.mailbox.item.categories.getAsync({ asyncContext: event },
        (asyncResult) => {
        if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
            const categories = asyncResult.value;
          if (categories && categories.length > 0) {
            if (
              categories.some((r) => r.displayName.includes("Meetings"))
            ) {
              CreateCMSRequest(event);
            }
          } else {
            console.log("There are no categories assigned to this item.");
          }
        } else {
          console.error("Failed to get categorie",asyncResult.error);
        }
      });
  }
  function CreateCMSRequest(event){
    let mailboxItem = Office.context.mailbox.item;
        mailboxItem.subject.getAsync({ asyncContext: event }, (asyncResult) => {
          if (asyncResult.status === Office.AsyncResultStatus.Failed) {
            console.log(asyncResult.error.message);
          } else {
		    console.log(asyncResult.value);
            let request = JSON.parse(localStorage.getItem("xyz")); // <------ IT FAILS HERE
            localStorage.setItem("xyz", JSON.stringify(request)); // <------ IT FAILS HERE AS WELL
            request = JSON.parse(localStorage.getItem("xyz")); // <------ IT FAILS HERE AS WELL
            let randomVal = Math.floor(Math.random() * 10) + 10; // <------ IT FAILS HERE AS WELL
          }
        });
  }
Office.onReady() 
    .then( function() { 
      console.log("^^^^office is now ready");
      if (Office.context.platform === Office.PlatformType.PC
        || Office.context.platform === Office.PlatformType.Mac
        || Office.context.platform === Office.PlatformType.OfficeOnline) {
      Office.actions.associate("onAppointmentSendHandler", onItemSendHandler);
    }
    });

**manifest.xml**
<Hosts>
    <Host Name="Mailbox"/>
  </Hosts>
  <Requirements>
    <Sets>
      <Set Name="Mailbox" MinVersion="1.1"/>
    </Sets>
  </Requirements>
  .
  .
  .
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
    <Requirements>
      <bt:Sets DefaultMinVersion="1.12">
        <bt:Set Name="Mailbox" />
      </bt:Sets>
    </Requirements>
	<Hosts>
      <Host xsi:type="MailHost">
        
        <Runtimes>
          
          <Runtime resid="WebViewRuntime.Url">
            
            <Override type="javascript" resid="JSRuntime.Url"/>
          </Runtime>
	.
	.
	.
	
          <ExtensionPoint xsi:type="LaunchEvent">
            <LaunchEvents>
              <LaunchEvent Type="OnAppointmentSend" FunctionName="onAppointmentSendHandler" SendMode="SoftBlock" />
            </LaunchEvents>
            
            <SourceLocation resid="WebViewRuntime.Url"/>
          </ExtensionPoint>
		  .
		  
	<bt:Urls>
		<bt:Url id="JSRuntime.Url" DefaultValue="https://localhost:3000/officeappsoutlook/launchevent.js" />

_Ask your question here._

**Comment by davidchesnut** [comment]
Hi @satyamkatiyar 

This repo is for questions about the samples. If you could post this question on https://stackoverflow.com using the [outlook-web-addins] tag that would be the best place to get help with this question.

Taking a look at the code, I have a few suggestions:

-  On Windows you get a JS-only runtime that runs event code (not a full webview/browser) so you can’t use any APIs that would require the full webview. For example there is no window object, and likely no JSON object either that you can call methods on.
- Also you need to call event.completed() in the asynchronous calls when they are completed. For example, you pass the event object to CreateCMSRequest, but you also need to call event.completed() after processing the asyncResult in the callback. If you don't handle the completed call when your code is done running, the JS runtime could behave oddly, or shut down before your code is done.
- Instead of using localstorage, you may want to take a look at [Get and set add-in metadata for an Outlook add-in](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/metadata-for-an-outlook-add-in) to persist data.

Hope this helps,
David
