### ISSUE TITLE
VersionOverrides link is broken in samples

### ISSUE THREAD

**Issue by Kevin-Wallace-Uptime** [OfficeDev/Office-Add-in-samples#528]
**URL of sample**

[URL](http://schemas.microsoft.com/office/taskpaneappversionoverrides)

**Describe the bug**

Unable to get the schema that is listed in the above link

**To Reproduce**

1. _Go to http://schemas.microsoft.com/office/taskpaneappversionoverrides
2. See: The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Expected behavior**

Not sure, but I would think it would be something valid at least

**Screenshots**

_If applicable, add screenshots to help explain your problem._

**Environment**
- Platform: Mac
- Host: Word
- Office version number: 16.73
- Operating System: MacOS

**Additional context**

_Add any other context about the problem here._

**Comment by Rick-Kirkham** [comment]
@Kevin-Wallace-Uptime Where are you seeing this link?

**Comment by Kevin-Wallace-Uptime** [comment]
It's in pretty much every manifest file: https://github.com/OfficeDev/Office-Add-in-samples/blob/8274b3f1aa54c24eab26d7de06053c280192a313/Samples/excel-insert-file/manifest.xml#L2

**Comment by Rick-Kirkham** [comment]
Those aren't URLs. Those are XML namespace URIs. They uniquely identify an XML schema, but they aren't necessarily URLs that you can navigate to. The schemas are at: https://learn.microsoft.com/en-us/openspecs/office_file_formats/ms-owemxml/c6a06390-34b8-4b42-82eb-b28be12494a8
