### ISSUE TITLE
Office-Add-in-Microsoft-Graph-React - production redirectUri

### ISSUE THREAD

**Issue by captainR0bbo** [OfficeDev/Office-Add-in-samples#545]
> Note: This repo is only for questions related to its samples. If you have questions about how to use office.js or the Office developer platform, please post your question on https://stackoverflow.com. Tag your question with office-js or outlook-web-addins

**Question**

When we deploy an add-in using the concepts in this example, what would the redirect Uri be? In DEV this works because node is serving the https://localhost:3000/login/login.html file, but should that URL be in the context of an Outlook task pane or Dialog?

**Comment by Rick-Kirkham** [comment]
When you move an add-in from development to staging or production, you normally just replace the "localhost:xxxx" domain in URLs with  the production domain. E.g., "www.contoso.com".

**Comment by captainR0bbo** [comment]
Thanks Rick. I just realized the prodUrl in the webpack. Was forgetting the add-in was going to be served from a server and not just run locally in Outlook. That was silly. Thanks!
