### ISSUE TITLE
what are the exact prerequesites to install/side-load an Outlook add-in?

### ISSUE THREAD

**Issue by jol64** [OfficeDev/Office-Add-in-samples#546]
**Question**

I managed to find Get Add-In in my Windows Outlook 2019 and 2022 installations (two PCs), however they are both dimmed.
I tried options in https://www.technipages.com/outlook-get-add-ins-button-is-grayed-out/ except for the Exchange account, none worked or offered the relevant settings.

I want to use / enhance /develop for:
- local installation of Outlook 2019/2022 (at least initially)
- outlook being connected to a mail server supporting EAS but not being Exchange plus some accounts on outlook.com

I´d like to just install the "hello world" example. I can put up file shares or webservers (IIS or nginx), but the required structure is unfortunately only given by npm instructions. Also it is unclear how to overcome the dimmed issue.

Please advise and clariy the instructions.

Thanks, Joachim

**Comment by Rick-Kirkham** [comment]
@jol64 As I understand it you are working with the sample at [outlook-hello-world](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/hello-world/outlook-hello-world). Can you confirm that? 

At what step in the instructions do you get blocked? What do you expect to see and what do you actually see?

**Comment by jol64** [comment]
I want to start working from that example, but I was unable to install it as is. As I wrote, the button "Get Add-In" in Outlook is dimmed, and I haven´t found a way to get it working.

**Comment by Rick-Kirkham** [comment]
@samantharamon Can you take a look?

**Comment by samantharamon** [comment]
Hi @jol64,

Apologies for the delayed response. To install and load Outlook add-ins, your mail account must be connected to Microsoft 365 or an Exchange server. To learn more about this and other requirements, see [Outlook add-in requirements](https://learn.microsoft.com/office/dev/add-ins/outlook/add-in-requirements). 

If you require an account for development purposes, we'd like to invite you to join the [Microsoft 365 Developer Program](https://developer.microsoft.com/microsoft-365/dev-program). The program gives you access to a free developer sandbox with a 90-day renewable Microsoft 365 E5 license. This will allow you to test and develop add-ins for Outlook.

**Comment by Rick-Kirkham** [comment]
[like]  Ricky Kirkham reacted to your message:
________________________________

**Comment by jol64** [comment]
Configuring an outlook.com account activated Get.Add-In and I can browse Add-Ins provided by outlook.com, plus at the end there is "Add a custom add-in".
Frankly, requiring a connection to a service one doesn´t really need looks just plain wrong. I know a lot more users of the software Office/Outlook then the service. Looks like Microsoft wants to get rid of anyone using their software.

Now how does the add-in need to be structured on a web server or file system, not using npm?

**Comment by samantharamon** [comment]
Thank you for the feedback, @jol64. I'll be sure to pass it on to the relevant team for further review.

Your add-in files would follow a similar structure, but you'll need to specify the web server where the files are hosted in your manifest (basically, replace any `localhost` references with the hosting location). For reference, see the file structure and manifest of the [Outlook hello-world Office Add-in sample](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/hello-world/outlook-hello-world).

**Comment by joachimlindenberg** [comment]
@samantharamon Thanks. I downloaded a copy to local file system, renamed the manifests and was able to "add" from file. The Add-In then showed up when composing a new message, but pressing on it resulted in an error message "cannot load..." whatever.

in event viewer there was somewhat more details, apoligizes that my installation is German, rough translation added:
Add-In-Fehler  / Add-In-Error
   Leider kann das Add-In nicht geladen werden. Überprüfen Sie, ob eine Netzwerk- und/oder Internetverbindung besteht. 
   Unfortuantely the add-in cannot be loaded. Check whether a network or internet connection exists.
...

I looked at the manifest and noticed there are absolute URLs in it. Actually I think this is a design error though I don´t know whether add-ins in general suffer that issue or only the examples are not written using relative URLs. Anyone redistributing an add-in would have to update all URLs.  Thinking about modifications: is there a mechanism to sign add-ins?

**Comment by jol64** [comment]
sorry, was using wrong account to update, which obviously doesn´t trigger any bots..

**Comment by samantharamon** [comment]
@jol64 When you get a chance, could you share a snippet of your manifest, so that we could troubleshoot the issue further?

Regarding the URLs, they must be absolute links, so that the add-in can load the correct resources. I'll look into whether signing an add-in is supported. In the meantime, could you please share more details on the hosting setup you're planning for your add-in, so that we can help provide suggestions more suited to your context?

**Comment by jol64** [comment]
@samantharamon I used the original https://github.com/OfficeDev/Office-Add-in-samples/blob/main/Samples/hello-world/outlook-hello-world/manifest-localhost.xml renamed to manifest.xml, but when importing I used file system navigation rather than setting up a localhost based webserver (in fact the PC I tried on does run an IIS but with a certificate matching its FQDN on port 443.
For my own needs I can put this on a local web or file server, but with hard coded paths it is impossible to run distinct development, test and production sites. And no idea how one would test add-ins in a CI pipeline.
To me it looks like Microsoft never considered distribution channels or customers using Outlook client but not using Exchange.

**Comment by samantharamon** [comment]
@JuaneloJuanelo, is this something you could assist with further? Thank you.

**Comment by davidchesnut** [comment]
Hi @jol64, Just checking in on this issue and want to see if you need any assistance with your Outlook Add-in. To answer your question on a CI pipeline, The typical strategy is to use multiple manifests. For dev and testing you could use a manifest that points to a localhost server for dev/test on your own computer. If you are using a cloud pipeline for staging/production, again you could use a different manifest for each phase in the pipeline. manifest-local, manifest-staging, manifest-production. If you build an Outlook Add-in with Visual Studio, you'll see it takes a similar approach by using relative urls in the manifest when viewed in the project. When your run the build it builds the expected manifest. There's more information on how to configure the packaging at https://stackoverflow.com/questions/38491135/specify-value-for-remoteappurl-in-an-office-add-in-manifest

Hope this helps,
David

**Comment by joachimlindenberg** [comment]
@davidchesnut imho this is a poor workaround. But the reason I was not spending any time on the topic is the need for an exchange server
@samantharamon  any news w.r.t. that need?
Thanks,
Joachim
