### ISSUE TITLE
.NET7.0 rc2 threads disable  WASM Blazor

### ISSUE THREAD

**Issue by RaoulRSV** [OfficeDev/Office-Add-in-samples#548]
**URL of sample**

[ sample](https://github.com/RaoulRSV/BlazorWASMNET7RC)

Note that this sample was derived as a  .NET 7.0 rc2 from a sample named "javascript-interaction-blazor-wasm-dotnet6-master" found on github one year ago 

**Describe the bug**
Enabling threads disable Blazor interface startup

**To Reproduce**

1. open and run sample blazor interface appears
2. on blazor interface click on CallC# button then calllocalstaticmethod continue after brakepoints then check that  "localstaticmethodcalled" message appears
3. stop project then enable thread property  on .csproj and run the project for a second time then check that no blazor interface appears

**Expected behavior**
The blazor interface should appear as for the first run.
Note that another research on "blazor addin" (see #544) shows a similar behaviour :  DotNet.invokeMethodAsync is disabled by thread enabling

**Environment**
- Platform [PC desktop]: PC desktop
- Visual basic 2022 
- Operating System: windows 11 with .Net7.0 rc2

**Additional context**

This issue could be merged with #544

**Comment by aafvstam** [comment]
@RaoulRSV If I follow your steps, I indeed see the same issue. 

If I however read the blogpost [here](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-rc-2/) (and the comments below) it has not been applied for Blazor Web Assembly. The sample project in the blogpost was working, but that is in plain javascript ... not in Blazor. Also, the comments below indicate that for async Task handling threading is not needed.

We need to wait to get this into the code for Blazor Web Assembly for threading support.

**Comment by RaoulRSV** [comment]
@aafvstam You're right. Now I get it. Multithreading is not available for blazor yet be it with .net 7.0 rc2 or .NET 8.0 preview. I did misinterpret the blogpost you mention. It is about webworkers in plain javascript as you mentionned and seems to still have its own difficulties see [here](https://github.com/dotnet/runtime/issues/68162).
Thank you for your help
I close this issue
