### ISSUE TITLE
Missing c# breack points

### ISSUE THREAD

**Issue by Gioking** [OfficeDev/Office-Add-in-samples#549]
Hi, I can use the blazor webassembly template Offfice 365 word addin, anyway the are some question about the debug: I did try to set to false and true the property launchBrowser to see if breackpoint will stop the code at, but nothing, I did try to act in the application page in the browser but even from there no breackpoint is working, in this manner it is very difficult and time consuming to debug the code. Is there a way to solve this problem ?
Thank you

**Environment**
- Platform [PC desktop, Windows 10, Office OnPremise
- Host Word
- Office version number: 365
- Operating System: Windows 10
- Browser (if using Office Online):

**Comment by thaystg** [comment]
Can you try to create this csproj.user in your project like I did in this PR:
https://github.com/OfficeDev/Office-Add-in-samples/pull/456

![image](https://github.com/OfficeDev/Office-Add-in-samples/assets/4503299/3e128a46-9096-4449-bc84-9c794c2038b8)

**Comment by davidchesnut** [comment]
Thanks @thaystg! One minor change is to make sure the localhost port matches your server. For the Word sample it will be 7096 as follows:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <BlazorAppUrl>https://localhost:7096/</BlazorAppUrl>
    <InspectUri>{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}</InspectUri>
  </PropertyGroup>
</Project>
``` 

Also be sure to update your launchsettings.json file to set `"launchBrowser": false,` in all profiles. I'll submit a PR to update the Word and other Blazor samples so they support debugging in webview.

Cheers,
David

**Comment by Gioking** [comment]
Hi thank you very much for your support, I will try your settings.
Gio

**Comment by davidchesnut** [comment]
PR #596 updated the samples with the correct debug configurations, so that should resolve this issue. I'm closing this issue, but please let us know if you have any more questions. Thanks!

**Comment by Perfexiasrl2023** [comment]
Thank you David, I will give you a feedback as soon

**Comment by Gioking** [comment]
I have created an old-fashioned application to manage Docker containers in a simpler and, more importantly, visual way. I must tell you upfront that I haven't spent too much time on refining it, as I've been working on it during the evenings after dinner and on weekends. For years, I've used other people's code, and now I feel a duty to contribute my part. This is the first time I am making a repository public, so if you can offer any advice, including on the code of conduct on GitHub, it would be greatly appreciated.

Here you can see my project: https://gioking.github.io/DockerDeskSite/

Thank you,
Giovanni

**Comment by Gioking** [comment]
Sorry: this is the repo: https://github.com/Gioking/DockerDesk
