### ISSUE TITLE
Tutorial for excel insert file doesn't work

### ISSUE THREAD

**Issue by AaEll** [OfficeDev/Office-Add-in-samples#564]
**URL of sample**

[_URL linking to the sample that has the bug._
](https://github.com/OfficeDev/Office-Add-in-samples/tree/1f869ac66cb6a140e628fef263c4ada71ce8834c/Samples/excel-insert-file)

**Describe the bug**

I follow the steps for localhost testing but it doesn't load the addin.

**To Reproduce**

Open the index.js file.

Edit line 4 to refer to the localhost:3000 endpoint as shown in the following code.

const dataSourceUrl = "https://localhost:3000";
Save the file.

You need http-server to run the local web server. If you haven't installed http-server, you can do this with the following command:

npm install --global http-server
Use a tool such as openssl to generate a self-signed certificate that you can use for the web server. Move the cert.pem and key.pem files to the webworker-customfunction folder for this sample.

From a command prompt, go to the web-worker folder and run the following command:

http-server -S --cors . -p 3000
To reroute to localhost run office-addin-https-reverse-proxy. If you haven't installed this proxy, you can do it with the following command:

npm install --global office-addin-https-reverse-proxy
To reroute run the following in another command prompt:

office-addin-https-reverse-proxy --url http://localhost:3000
Follow the steps in [Run the sample](https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/excel-keyboard-shortcuts#run-the-sample), but upload the manifest-localhost.xml file for step 6.
**Expected behavior**

_A clear and concise description of what you expected to happen._

**Environment**
- Platform [PC desktop, Mac, iOS, Office Online]: Mac Office Online
- Host [Excel, Word, PowerPoint, etc.]: Excel
- Browser (if using Office Online): Chrome

**Comment by Rick-Kirkham** [comment]
@AaEll The instructions refer to a folder named webworker-customfunction, but I can't find any such folder in the sample. Where did you put the cert.pem and key.pem files?

**Comment by AaEll** [comment]
I tried putting the cert.pem and key.pem in two positions : 
/Office-Add-in-samples/Samples/excel-insert-file/ 
/Office-Add-in-samples/Excel-custom-functions/web-worker/

Steps I followed:
1. Changing const `dataSourceUrl = "https://localhost:3000";` in `index.js` 
2. `http-server -S --cors . -p 3000` in /Office-Add-in-samples/Samples/excel-insert-file/
3. `office-addin-https-reverse-proxy --url http://localhost:3000` in the same directory as the cert.pem and key.pem 

Following these instructions, both commands started a process as expected. However, did not lead to a functioning manifest-local.xml add-in.

**Comment by Rick-Kirkham** [comment]
@AaEll But what directory is the one with the cert.pem and key.pem?

**Comment by AaEll** [comment]
First I tried adding the cert.pem and key.pem in `~/Office-Add-in-samples/Samples/excel-insert-file/`

then after that didn't work, I deleted those files and generated new ones in `~/Office-Add-in-samples/Excel-custom-functions/web-worker/`

**Comment by Rick-Kirkham** [comment]
@davidchesnut Can you take a look at this? The instructions in the readme refer to folders that aren't there.

**Comment by davidchesnut** [comment]
Thanks @AaEll! Yes those steps are definitely wrong. I submitted #579 to update the steps. Thanks!
