### ISSUE TITLE
Example for MS projects?

### ISSUE THREAD

**Issue by Dylanb-dev** [OfficeDev/Office-Add-in-samples#577]
**Is your feature request related to a problem? Please describe.**

I would like an example for MS projects that includes what versions it supports etc as I am a little confused on what versions of MS projects you can create add-ins for.

**Comment by AlexJerabek** [comment]
Hi @Dylanb-dev,

The list of supported Project versions is found under [Office client application and platform availability for Office Add-ins](https://learn.microsoft.com/en-us/javascript/api/requirement-sets?view=common-js-preview#project)

Project currently only supports a small set of Common APIs that were released with the JS platform's launch in 2013. You can create a sample Project add-in through yo office in the article [Build your first Project task pane add-in](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/project-quickstart?view=common-js-preview).

Given the limited functionality that Project supports, we are not investing in further samples. You can request additional Project features in the [Microsoft 365 Developer Platform Tech Community](https://aka.ms/m365dev-suggestions).
