### ISSUE TITLE
idMSOs in PowerPoint?

### ISSUE THREAD

**Issue by elthombre** [OfficeDev/Office-Add-in-samples#582]
Can someone please help with this:

https://github.com/OfficeDev/office-fluent-ui-command-identifiers/issues/17

it has received no response. And, yes, it is also here:

https://stackoverflow.com/questions/76947307/idmsos-in-powerpoint

I am not sure where else to request assistance.

Looping through cells manually, as is suggested elsewhere, creates an incredible bottleneck. Applying via the Ribbon applies all-at-once and takes milliseconds vs. minutes.

This is in the current version of PowerPoint on Windows 11 but I do not believe the behavior to be any different with Windows 10 / previous version of PowerPoint.

We want to run the "Layout" -> "Cell Margins" -> "Narrow"

What is the idMSO / ExecuteMso tag with the 'Narrow' option?

Similarly, with table selected, on the "Home" tab, "Font" -> "Size" and the number?

**Comment by davidchesnut** [comment]
Hi @elthombre, Sorry to hear you've been stuck on this. I reached out to the team for that repo, so hopefully they will follow up on the original issue soon.
 
Cheers,
David

**Comment by elthombre** [comment]
@davidchesnut - thank you very much

**Comment by elthombre** [comment]
I was able to get these working through SendKeys. While this may be a fragile and kludgy way to implement, to offer some perspective: what previously took 2-3 minutes to process, now completes in about 30 seconds.

Those functionalities should be added and exposed in the API.

**Comment by davidchesnut** [comment]
@elthombre glad you found a workaround! The team on that repo is aware of the open issues, so I will close this here if that's okay. Thanks!
