### ISSUE TITLE
excel-insert-file not working as expected

### ISSUE THREAD

**Issue by lewis1573** [OfficeDev/Office-Add-in-samples#591]
**Question**
I try to run the sample on excel on the web, After doing all the steps.  A Contoso Sales Report be inserted with a table, but no date in the report. as shown in the below. 
![image](https://github.com/OfficeDev/Office-Add-in-samples/assets/77063576/47b43074-16fa-45ec-9a70-6d8323d7807c)
I've noticed "To use this sample, you'll need to join the Microsoft 365 Insider program",But this sample uses the web version of excel and I didn't find how to  join the Microsoft 365 Insider program for excel on the web. I need help. Thanks in advance.

**Comment by AlexJerabek** [comment]
Hi @lewis1573,

I'm seeing the same behavior in the sample. I'll start investigating.

**Comment by AlexJerabek** [comment]
Hi @lewis1573,

I created https://github.com/OfficeDev/Office-Add-in-samples/pull/593 to fix this issue. To test it yourself, change lines 51-57 in index.js to this:
```
        // Get data from your REST API. For this sample, the JSON is fetched from a file in the repo.
        let json;
        let response = await fetch(dataSourceUrl + "/data.json");
        if (response.ok) {
          json = await response.json();
        } else {
          console.error("HTTP-Error: " + response.status);
          return;
        }
```

Then follow the [instructions to run the sample locally](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/excel-insert-file#configure-a-localhost-web-server-and-run-the-sample-from-localhost).

Please let me know if that works for you. Thanks!

**Comment by lewis1573** [comment]
Hi @AlexJerabek ,Sorry for my late feedback, I tested it in the web version of excel and it works fine, thank you for your help!
