### ISSUE TITLE
Azure CLI not found when running npm run configure-sso

### ISSUE THREAD

**Issue by kirilvalev** [OfficeDev/Office-Add-in-samples#597]
**Describe the bug**

When I run run `npm run configure-sso` I am trapped in a loop, which always shows:

Azure CLI is not installed.  Installing now before proceeding - this could take a few minutes.

Problem is, that Microsoft Azure CLI app name is either `Microsoft Azure CLI (32-bit)` or `Microsoft Azure CLI (64-bit)` but the script checks on for `Microsoft Azure CLI` without the suffix.

**Comment by mikewalker74** [comment]
Still seeing this issue, not sure of a work around for this at the moment.

**Comment by davidchesnut** [comment]
Hi @mikewalker74, can you provide some steps to reproduce the issue?

I gave this a try by uninstalling the Azure CLI, then running `yo office` and creating a new SSO project. I then ran `npm run configure-sso`. It popped up the warning that it needed to install Azure CLI, at which point it installed Azure CLI (32 bit). 

Are you doing these same steps, or something different? Are you seeing any errors?

As a workaround you could try installing the [Azure CLI directly](https://learn.microsoft.com/cli/azure/install-azure-cli-windows?tabs=azure-cli). Does that work?

Thanks!
David

**Comment by mikewalker74** [comment]
I tried the uninstall azure cli as it wasn't originally installed the first time I tried to run configure sso it asked and installed the 32 bit. I also installed the 64 bit.. I worked around the problem by changing the if logic to carry on as if installed in the configure sso script. I didn't dig into the code to check how it validated the install was successful.

Summary
Tried manual install, uninstall and install done by the script and also 64bit azure cli manual install.

Fix by changing the logic on the check if azure installed to  the opposite and it worked fine. Sorry not on machine to see exact code I changed. Will update if can tomorrow.

Mike Walker
________________________________

**Comment by davidchesnut** [comment]
Hi @mikewalker74, if the code fix is to the office-addin-sso package, you can submit the PR against the original repo here: https://github.com/OfficeDev/Office-Addin-Scripts/tree/master/packages/office-addin-sso

Thank you!
David

**Comment by mikewalker74** [comment]
It wasn't a fix more of a hack to be honest which is not robust to checkin.

Mike Walker
________________________________
