### ISSUE TITLE
Office-Add-in-NodeJS-SSO - change root url 

### ISSUE THREAD

**Issue by aureliensolassier** [OfficeDev/Office-Add-in-samples#598]
Hello, I am learning how to make an office addin but I don't understand in the Office-Add-in-NodeJS-SSO template. 
It works fine but if I change  const rootUrl = '/me/drive/root/children'; (getfilesroute.js)
and i replace by const rootUrl = '/me/drive/root'; 
Nothing works anymore 
(error: if (err.errorMessage.indexOf('AADSTS500133') !== -1) {
^TypeError: Cannot read properties of undefined (reading 'indexOf')
by testing via postman it works
If anyone can help me understand that would be great.

**Comment by davidchesnut** [comment]
Hi @aureliensolassier,

I think what is happening is that the code is expecting a list of files returned in the body. But by changing to the root you are not getting a list of files. So the following code (around line 64) which expects to process a list can't find the index of any files in the array.

```javascript
   const oneDriveItems = graphData["value"];
   for (let item of oneDriveItems) {
      itemNames.push(item["name"]);
    }
``` 

Also be aware of this line which passes parameter filters that can alter the returned values. This may need to change based on which API you want to call.

```javascript
   const params = '?$select=name&$top=10';
```

You'll need to adjust the code to handle the response for whatever Microsoft Graph API you call.

Hope this helps,
David
