### ISSUE TITLE
Install Addin fails

### ISSUE THREAD

**Issue by JonathanClark11** [OfficeDev/Office-Add-in-samples#613]
**URL of sample**

[_URL linking to the sample that has the bug._](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/tutorials/outlook-tutorial/Git%20the%20gist)

**Describe the bug**

I'm developing a new addin and I couldn't install the default outlook addin on a fresh outlook account (this one).  I used the code from https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/tutorials/outlook-tutorial/Git%20the%20gist.

Every time I try to install I get a vague error:

"
Installation failed

Add-in installation failed.
"

**To Reproduce**

create fresh outlook account in outlook web
    download sample code above

$ npm install
$ npm build
$ npm run dev-server

    Confirm app runnning at https://localhost:3000/taskpane.html
    Go back to outlook web, open a message to me, open "get addins" -> My addins -> Custom Addins -> Add from File...
    Select manifest.xml file. 

Error thrown.

Is this a bug or am I supposed to setup something else?

**Expected behavior**

Installation succeeds

**Screenshots**

**Environment**
- Platform [PC desktop, Mac, iOS, Office Online]: Mac for coding, outlook web for testing installs.
- Host [Excel, Word, PowerPoint, etc.]: outlook web
- Office version number: N/A
- Operating System: Sonoma
- Browser (if using Office Online): Firefox (also tried safari)

**Additional context**

_Add any other context about the problem here._

**Comment by AlexJerabek** [comment]
Hi @JonathanClark11,

I'm sorry to hear you're having issues with the sample. Are you having the same issues following the step-by-step instructions in the [Outlook quickstart](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?view=excel-js-preview&tabs=yeomangenerator)?

**Comment by JonathanClark11** [comment]
It still failed after going through the quickstart tutorial.  It seems to be a MS account-specific issue.  I tried on a separate account at it all worked normally.  Possible the account was blocked?

**Comment by AlexJerabek** [comment]
Yeah, it could be some admin settings that block add-ins. We recommend getting a free developer tenant through the [M365 Developer Program](https://developer.microsoft.com/en-us/microsoft-365/dev-program). That way, you'll be able to configure the admin enviornment however you need. It also allows you to test your add-in without using your actual Outlook account.

Since it seems like this isn't an issue with the sample, I'm going to close this issue. Please let me know if you have any other issues.
