### ISSUE TITLE
Better way to handle unidentified image URL with  WebImageCellValue 

### ISSUE THREAD

**Issue by varunnaladham-smc** [OfficeDev/Office-Add-in-samples#630]
Hi team, thanks for your documents with image datatypes , its useful and powerful feature  

i am trying to fetch images on a selected range having the image filename in each of the cells, i was using  WebImageCellValue datatype. all good, but when the image not found or not available, cell value is set displayed as **#CONNECT!**

Refer to here:
![image](https://github.com/OfficeDev/Office-Add-in-samples/assets/130931870/9c309f6e-22e4-4896-a3c8-bcbf07a187b8)

However, if in case image not available,i want to keep original call value which is original  imagefile name back in the cell ( sourceRange.values[i][j]) 

any suggestions to fix this pls....

current Code : 
    Excel.run(function (ctx) {
        // Create a proxy object for the selected range and load its properties
        var sourceRange = ctx.workbook.getSelectedRange().load("values, rowCount,columnCount,text");
        // Run the queued-up command, and return a promise to indicate task completion
        return ctx.sync()
            .then(function () {
                //Handle use error when cells are selected
                if (sourceRange.values[0][0] == "" & sourceRange.rowCount == 1 & sourceRange.columnCount == 1) { console.log("No Cells selected");  throw new Error("Please select the cells with SFC Code"); }
                for (var i = 0; i < sourceRange.rowCount; i++) {
                    for (var j = 0; j < sourceRange.columnCount; j++) {
                        if (sourceRange.values[0][0] != "") { //select only cells with values
                            var cellToHighlight;
                            cellToHighlight = sourceRange.getCell(i, j); //Get Cell to Insert Images
                            var imageUrl = imgurl + sourceRange.values[i][j] + ".jpg" //Set the image 
                            var imageAltText = sourceRange.values[i][j]; // Set the Cell value
                            //console.log("calling download image: " + imageUrl)
                            //Create a web image object and assign the image details.
                            const webImage = {
                                type:
                                    "WebImage" /* The string equivalent of `Excel.CellValueType.webImage`. */,
                                address: imageUrl,
                                altText: imageAltText,
                            }
                            // Insert web image into the active cell.
                            cellToHighlight.valuesAsJson = [[webImage]];
                        }
                    }
                }
            })
               // sync the context to run the previous API call, and return.
            .then(ctx.sync);
    })
    .catch(errorHandler);
}

**Comment by alison-mk** [comment]
Hello @varunnaladham-smc, thank you for submitting a question. Data types do offer error handling support, see this article for more details: https://learn.microsoft.com/en-us/office/dev/add-ins/excel/excel-data-types-concepts#improved-error-support

I also put together a Script Lab sample that shows how to set an error value in a cell, then check if a cell contains an error and update the cell if it does contain an error. This sample uses the #BUSY! error, but you can follow a similar pattern for the #CONNECT! error. Here is the Script Lab sample: 
https://gist.github.com/alison-mk/9d66c10857477adb5e9c264c0cb0da1b

I will add this Script Lab sample to our documentation and update this PR when I've done that.

Thanks, 
Alison

**Comment by alison-mk** [comment]
Closing issue. Script Lab sample update is complete.
