### ISSUE TITLE
Missing scopes (scp) in Bearer token from Azure AD

### ISSUE THREAD

**Issue by pobereder** [OfficeDev/Office-Add-in-samples#632]
> Note: This repo is only for questions related to its samples. If you have questions about how to use office.js or the Office developer platform, please post your question on https://stackoverflow.com. Tag your question with office-js or outlook-web-addins

**Question**

Hello, the bearer token that is returned from Azure AD, when executing the following code:

const accessToken = await Office.auth.getAccessToken({
      allowSignInPrompt: true,
      allowConsentPrompt: true,
      forMSGraphAccess: true,
    });

does not contain the scp parameter. Therefore the code fails at:

const tokenScopes = jwt.decode(oboRequest.oboAssertion).scp.split(" ");

throwing the exception: TypeError: Cannot read properties of undefined (reading 'split') 

I am hosting the client-side code on an Azure Static Web App and the api, where the auth happens on its integrated Function App.
I set up the App registration as in the guides:
https://learn.microsoft.com/en-us/office/dev/add-ins/publish/deploy-office-add-in-sso-to-azure?tabs=windows
https://learn.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs

I already opened multiple support requests at MS but they were not able to help me yet.
Could you please help me with this? What could be the reason the scp paramter is missing.

Br Paul

**Comment by alison-mk** [comment]
Hi @pobereder, thank you for submitting this question about our Office-Add-in-NodeJS-SSO sample. @davidchesnut Could you take a look, or reassign as necessary?

**Comment by pobereder** [comment]
Hi, sorry, I found the issue, I had a wrong URI in the redirect URIs after changing to a custom domain.
