### ISSUE TITLE
Unable to sideload the example

### ISSUE THREAD

**Issue by zengem** [OfficeDev/Office-Add-in-samples#641]
**Question**

I'm following the instruction on the following page. 
https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/outlook-tutorial

At step **Test the generated add-in**, when I run <npm start>, the following error is shown:

```
> office-addin-taskpane-js@0.0.1 start
> office-addin-debugging start manifest.xml

Debugging is being started...
App type: desktop
Starting the dev server... (webpack serve --mode development)
The dev server is running on port 3000. Process id: 3709
Sideloading the Office Add-in...
Error: Unable to start debugging.
Error: Unable to sideload the Office Add-in. 
Error: Sideload to the Outlook app is not supported.
```

**Comment by samantharamon** [comment]
Hi @zengem. Thanks for reaching out. On which Outlook client and version are you testing this tutorial?
