### ISSUE TITLE
Word Addin in NET CORE 7.0 with MVC

### ISSUE THREAD

**Issue by ArielTommarello** [OfficeDev/Office-Add-in-samples#647]
Hello how are you? i beeen researching the razor web assembly for Word Addin , and i tried to replicate in .NET 7  but with MVC , you think that i can do it? Because always i do that i have a lot of issues with webroot and more. I ve tried to replicate some things of your code in Razor but i dont have any chance?
Can you give me a hand in clarify why always i have a WebRoot issue in the debuger?

Thank You

**Comment by davidchesnut** [comment]
Hi @ArielTommarello, I'm not aware of any limitations with using .NET 7 with the Razor web assembly. What is the error you are seeing? 

BTW: There's a similar Q&A on stackoverflow about setting up on .NET 7. In case this helps with your scenario [How to add Blazor Webassembly to an existing ASP.NET Core web app with .NET 7?](https://stackoverflow.com/questions/75775295/how-to-add-blazor-webassembly-to-an-existing-asp-net-core-web-app-with-net-7)

**Comment by ArielTommarello** [comment]
I hope this email finds you well. I appreciate your prompt response.

I'm pleased to inform you that I've managed to make it work, although not
using the method provided on the mentioned page. Instead, I successfully
implemented it by adapting an example I found on GitHub, which was already
developed by someone else.

However, I've encountered a new challenge. While I've successfully
integrated it with my API, I've discovered that a crucial part of my
authentication process involves retrieving a saved subscription from Word
XML properties. According to my research, this requires utilizing the
OfficeJS API in JavaScript. Although it seems to be functioning, it causes
issues during the page rendering, breaking the layout.

Have you ever encountered such a scenario? Is there a method you recommend
to call these properties after the page has finished rendering? Your
insights would be immensely helpful.

Thank you for your time and assistance.

**Comment by ArielTommarello** [comment]
Hi how are you?
Yes i tried all but its not working, maybe is an issue with some of the
office.js things idk.
My problem is that i cannot make a call to the javascript getCustomPartsXml
that i have in my js and put in my authorization method that i have in the
cshtml.cs because when i call that i have a problem with the prerenderizing.
Right now i 've trying to put all in a controller so the pages can
renderize and i can do the authentication thing.
But if you have something to solve that problem i appreciate it so much.
Thank You!

Ariel

**Comment by davidchesnut** [comment]
Is it possible to share a small code sample that reproduces the problem you are seeing? Thanks!

**Comment by ArielTommarello** [comment]
Hello, yeah but i do a rollover because i think that its a problem with the
office.js because when i enter to this code, i have problems with the
context, and i dont know if it i do the entire html project in cshtml with
net 7 or its a problem with references to the API, but i have problems with
the Context part, its like thats undefined or something like that i send
you a image. If you can help me with this issue i realy appreciate it-

(function () {
    "use strict";

    var messageBanner;

    // The initialize function must be run each time a new page is loaded.
    Office.initialize = function (reason) {
        console.log("here1");
        $(document).ready(function () {
            // Initialize the notification mechanism and hide it
            console.log("here2");
            var element = document.querySelector('.MessageBanner');
            messageBanner = new components.MessageBanner(element);
            messageBanner.hideBanner();

            // If not using Word 2016, use fallback logic.


            //if (!Office.context.requirements.isSetSupported('WordApi',
'1.1')) {
            //    $("#template-description").text("This sample displays the
selected text.");
            //    $('#button-text').text("Display!");
            //    $('#button-desc').text("Display the selected text");

            //    $('#highlight-button').click(displaySelectedText);
            //    return;
            //}


            $("#template-description").text("This sample highlights the
longest word in the text you have selected in the document.");
            $('#button-text').text("Highlight!");
            $('#button-desc').text("Highlights the longest word.");

            loadSampleData();

            // Add a click event handler for the highlight button.
            $('#highlight-button').click(hightlightLongestWord);
        });
    };

    function loadSampleData() {
        // Run a batch operation against the Word object model.
        Word.run(function (context) {
            // Create a proxy object for the document body.
            var body = context.document.body;

            // Queue a commmand to clear the contents of the body.
            body.clear();
            // Queue a command to insert text into the end of the Word
document body.
            body.insertText(
                "This is a sample text inserted in the document",
                Word.InsertLocation.end);

            // Synchronize the document state by executing the queued
commands, and return a promise to indicate task completion.
            return context.sync();
        })
            .catch(errorHandler);
    }

    function hightlightLongestWord() {
        Word.run(function (context) {
            // Queue a command to get the current selection and then
            // create a proxy range object with the results.
            var range = context.document.getSelection();

            // This variable will keep the search results for the longest
word.
            var searchResults;

            // Queue a command to load the range selection result.
            context.load(range, 'text');

            // Synchronize the document state by executing the queued
commands
            // and return a promise to indicate task completion.
            return context.sync()
                .then(function () {
                    // Get the longest word from the selection.
                    var words = range.text.split(/\s+/);
                    var longestWord = words.reduce(function (word1, word2)
{ return word1.length > word2.length ? word1 : word2; });

                    // Queue a search command.
                    searchResults = range.search(longestWord, { matchCase:
true, matchWholeWord: true });

                    // Queue a commmand to load the font property of the
results.
                    context.load(searchResults, 'font');
                })
                .then(context.sync)
                .then(function () {
                    // Queue a command to highlight the search results.
                    searchResults.items[0].font.highlightColor = '#FFFF00';
// Yellow
                    searchResults.items[0].font.bold = true;
                })
                .then(context.sync);
        })
            .catch(errorHandler);
    }


    function displaySelectedText() {

Office.context.document.getSelectedDataAsync(Office.CoercionType.Text,
            function (result) {
                if (result.status === Office.AsyncResultStatus.Succeeded) {
                    showNotification('The selected text is:', '"' +
result.value + '"');
                } else {
                    showNotification('Error:', result.error.message);
                }
            });
    }

    //$$(Helper function for treating errors,
$loc_script_taskpane_home_js_comment34$)$$
    function errorHandler(error) {
        // $$(Always be sure to catch any accumulated errors that bubble up
from the Word.run execution., $loc_script_taskpane_home_js_comment35$)$$
        showNotification("Error:", error);
        console.log("Error: " + error);
        if (error instanceof OfficeExtension.Error) {
            console.log("Debug info: " + JSON.stringify(error.debugInfo));
        }
    }

    // Helper function for displaying notifications
    function showNotification(header, content) {
        $("#notification-header").text(header);
        $("#notification-body").text(content);
        messageBanner.showBanner();
        messageBanner.toggleExpansion();
        setTimeout(function () {
            messageBanner.hideBanner();
        }, 10000);
    }




})();



[image: image.png]

thanks Ariel

**Comment by aafvstam** [comment]
@ArielTommarello Sorry to break in here, from what I read you are trying to implement a Server Side web, using MVC (given the fact that you use cshtml vs razor files). The Office JS API is required to be running on the client. That is why the Blazor Samples in this repo are using WASM to be able to run the .NET code on the client machine (and interop with JS to use the Office JS API options).

Do you have a test project that I can look into?

.NET 8 allows to build hybrid Server Side Rendering and Client Side Rendering solutions. I'll be working on this the upcoming weeks.

**Comment by ArielTommarello** [comment]
Hello! No problem.
I think that i solve the problem, but a new issue raise.
Right now i can access to office api js and insert things in the document
in a Net 7 environment throw the word api. But i need the Custom properties
of the document so i can sign in the user without the SSO of Microsoft. The
problem is for this to work i need the Word Api 1.3 or more newer, for that
i need to use word 2019 or word 365.
But when i uses this programs my SSO microsoft authenticator not works ,
you can login in microsoft but when the addin have to redirect you to Word
its not happening and a ERROR 500 local host cant handles the requests
appears in the screen, but i dont know why. I suspect that is a problem
with a cookie that you catch in Word-Win32 16.0.1.js
But i cant see the problem, maybe you can help me.
About the code sample, maybe i can send you that in the weekend because i
have to adapt to a new project for security of my company.
Thank you and we are in contact so i send you the test project.

**Comment by davidchesnut** [comment]
Hi @ArielTommarello, 

For SSO you should already be signed in to Word. When you open the add-in and it calls getAccessToken, you should not see another sign-in prompt. If you do, then likely your fallback code is running that uses MSAL to sign in. Can you confirm if getAccessToken is returning an error when you call it?

Thanks!
David
