### ISSUE TITLE
doc: broken image links on Readme.md of hello-world

### ISSUE THREAD

**Issue by HashidaTKS** [OfficeDev/Office-Add-in-samples#666]
**URL of sample**

https://github.com/OfficeDev/Office-Add-in-samples/blob/main/Samples/hello-world/outlook-hello-world/README.md

**Describe the bug**

The following image links are broken.

```

   ![Message compose window in the new Outlook on the web with Get Add-ins option highlighted.](https://raw.githubusercontent.com/OfficeDev/office-js-docs-pr/master/docs/images/outlook-on-the-web-new-get-add-ins.png)

   ![Add-ins for Outlook dialog box in the new Outlook on the web with My add-ins selected.](https://raw.githubusercontent.com/OfficeDev/office-js-docs-pr/master/docs/images/outlook-on-the-web-new-my-add-ins.png)

   ![Manage add-ins screenshot pointing to Add from a file option.](https://raw.githubusercontent.com/OfficeDev/office-js-docs-pr/master/docs/images/outlook-sideload-desktop-add-from-file.png)

   ![Outlook on the web store dialog with My add-ins selected.](https://raw.githubusercontent.com/OfficeDev/office-js-docs-pr/master/docs/images/outlook-sideload-store-select-add-ins.png)

   ![Manage add-ins screenshot pointing to Add from a file option.](https://raw.githubusercontent.com/OfficeDev/office-js-docs-pr/master/docs/images/outlook-sideload-desktop-add-from-file.png)
```

**To Reproduce**

Open https://github.com/OfficeDev/Office-Add-in-samples/blob/main/Samples/hello-world/outlook-hello-world/README.md

**Expected behavior**

The images are displayed.

**Screenshots**

![image](https://github.com/OfficeDev/Office-Add-in-samples/assets/15982708/7bfc9998-9c0a-424d-9732-2a0332a99052)

![image](https://github.com/OfficeDev/Office-Add-in-samples/assets/15982708/2e8a53b1-950f-48fa-8cf5-c47c55136329)

**Environment**

Chrome

**Additional context**

N/A

**Comment by AlexJerabek** [comment]
Thanks for reporting this @HashidaTKS.

@samantharamon, could you please investigate?

**Comment by samantharamon** [comment]
Thanks for reaching out, @HashidaTKS. I've cleaned up and reorganized the sample's README, which takes care of the broken images (see #667). The PR is currently in review. Please note that once the changes are merged, this issue will automatically close. However, if you need additional assistance, please don't hesitate to open a new GitHub issue.
