### ISSUE TITLE
Word Add-in in NET CORE 8 with blazor

### ISSUE THREAD

**Issue by danielpastoor** [OfficeDev/Office-Add-in-samples#668]
Will there be a example template for the office word add-in with .net 8 and blazor?

**Comment by aafvstam** [comment]
Yes, I will work on that the upcoming weeks. Keep an eye on my fork, you most likely will find a proto there soon!

**Comment by aafvstam** [comment]
I just created a new Pull Request #669 to upgrade the Office Blazor Sample project to .NET 8. Once approved you should be able to run that and close this issue.

**Comment by danielpastoor** [comment]
Thank you
