### ISSUE TITLE
Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize

### ISSUE THREAD

**Issue by RA-Davies** [OfficeDev/Office-Add-in-samples#691]
<i> [webpack-dev-server] 404s will fallback to '/index.html'
10% building 0/11 entries 16/26 dependencies 0/16 modulesC:\Software Development\open-graph-outlook-auth\Office-Add-in-samples\Samples\auth\Office-Add-in-Microsoft-Graph-React\node_modules\source-map\lib\read-wasm.js:8
      throw new Error("You must provide the URL of lib/mappings.wasm by calling " +
            ^

Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
    at readWasm (C:\Software Development\open-graph-outlook-auth\Office-Add-in-samples\Samples\auth\Office-Add-in-Microsoft-Graph-React\node_modules\source-map\lib\read-wasm.js:8:13)
    at wasm (C:\Software Development\open-graph-outlook-auth\Office-Add-in-samples\Samples\auth\Office-Add-in-Microsoft-Graph-React\node_modules\source-map\lib\wasm.js:25:16)
    at C:\Software Development\open-graph-outlook-auth\Office-Add-in-samples\Samples\auth\Office-Add-in-Microsoft-Graph-React\node_modules\source-map\lib\source-map-consumer.js:264:14

Node.js v20.9.0

> Note: This template is only for reporting bugs about samples in this repo. If you have a product bug to report about Office web Add-ins, please submit the issue at [https://github.com/OfficeDev/office-js/issues](https://github.com/OfficeDev/office-js/issues/new). This will help us respond to your issue faster.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

**URL of sample**

_URL linking to the sample that has the bug._

**Describe the bug**

_A clear and concise description of what the bug is._

**To Reproduce**

1. _Go to '...'_
2. _Click on '....'_
3. _Scroll down to '....'_
4. _See error_

**Expected behavior**

_A clear and concise description of what you expected to happen._

**Screenshots**

_If applicable, add screenshots to help explain your problem._

**Environment**
- Platform [PC desktop, Mac, iOS, Office Online]: ______
- Host [Excel, Word, PowerPoint, etc.]: ______
- Office version number: ______
- Operating System: ______
- Browser (if using Office Online): ______

**Additional context**

_Add any other context about the problem here._

**Comment by AlexJerabek** [comment]
Hi @RA-Davies,

Could you please fill out the issue template? That will help us triage and understand where things are going wrong in the sample.
