### ISSUE TITLE
Need admin privs to npx install, no?

### ISSUE THREAD

**Issue by jeffspc88mx** [OfficeDev/Office-Add-in-samples#699]
I'm noob so maybe it's understood by all, but I didn't have success with npx ... install until I executed in an admin environment. This isn't mentioned in the read.me (is it?) but, again, maybe everyone knows that already? If not, perhaps 'run as admin' should be mentioned? 

Anyway thanks for all this guidance - I'm an old v1.0 Excel user (!) and the way we 'macro' has sure changed over the years. This'll be my first go with the latest js architecture.

**Comment by AlexJerabek** [comment]
Thanks for reporting this @jeffspc88mx. You're not the first person to mention this, but I don't think I've ever needed to run these samples in admin mode.  Did this happen for you with a particular sample or is this a general issue with all Excel samples? 

Also, just to check, is everything working fine in admin mode?

**Comment by jeffspc88mx** [comment]
Understood. I'm working with the Excel Hello World add-in sample. Works great otherwise. I suspect the permission issue is because I'm using a managed corporate laptop, not my personal one. Thanks for checking in.
