### ISSUE TITLE
Converting Outlook VSTO add-in to web add-in

### ISSUE THREAD

**Issue by ravenbao1** [OfficeDev/Office-Add-in-samples#752]
> Note: This repo is only for questions related to its samples. If you have questions about how to use office.js or the Office developer platform, please post your question on https://stackoverflow.com. Tag your question with office-js or outlook-web-addins

**Question**

Hi, we have been using a VSTO add-in in Outlook and I understand that VSTO add-ins are not supported in the new Outlook, is there any easy way to migrate it to web add-in, or, is it possible to provide a very basic template of a web add-in that simply sends the user a prompt when there is an external recipient detected

Basically I need a sample of how such a prompt-based add-in can be created in JavaScript

**Comment by AlexJerabek** [comment]
Hi @ravenbao1,

Thank you for reaching out. Please check out our article on the new Outlook for Windows and the list of supported scenarios: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/one-outlook.

For your scenario in particular, are you looking to prompt the user when they are sending an email or receiving it?

(Tagging @samantharamon to follow-up.)

**Comment by ravenbao1** [comment]
@AlexJerabek prompt the user when they are sending an email - if it's being sent to one or more external recipients

Thank you very much!

**Comment by AlexJerabek** [comment]
Sounds like the Smart Alerts feature would suit your needs. Here's the article documenting that: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/onmessagesend-onappointmentsend-events?tabs=windows. Here's a sample that shows using the feature to check for missing attachments: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough?tabs=xmlmanifest.

Please let me know if that will get you going in the right direction. Thanks!
