### ISSUE TITLE
Example works only in OWA

### ISSUE THREAD

**Issue by Wh4teverr** [OfficeDev/Office-Add-in-samples#753]
I implemented the plugin via ECP and everything works properly in the WEB version.

However, in the classic version of Outlook, the plug-in starts, but the javascript does not work, it seems that the Office.onReady method never executes. Do you know what is the reason for this?

**Comment by AlexJerabek** [comment]
Hi @Wh4teverr,

Thanks for reporting this issue. However, could you please specify to which sample you are referring?

**Comment by Wh4teverr** [comment]
Yes, of course. I am referring to outlook-hello-world sample.

I mean: https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/hello-world/outlook-hello-world

**Comment by samantharamon** [comment]
Thanks for providing the sample, @Wh4teverr. When you get a chance, could you provide the version and channel of your classic Outlook on Windows client? And to clarify, when you say you implemented the add-in via ECP, are you referring to this deployment method: [Deploy add-ins in the Microsoft 365 admin center](https://learn.microsoft.com/microsoft-365/admin/manage/manage-deployment-of-add-ins)?

I tested locally installing the manifest and also deploying it via the Microsoft 365 admin center and confirmed that the add-in runs as expected in both Outlook on the web and on Windows (classic and new). If you locally install the manifest, does the add-in work in your Outlook desktop client?
