### ISSUE TITLE
Sample: Outlook-Add-in-SSO-NAA

### ISSUE THREAD

**Issue by GrumpyAL** [OfficeDev/Office-Add-in-samples#759]
**Question**

Should the acquireTokenSilent() part of this sample work?  I am trying to evaluate potential user experience changes for our add-in and determine when a login may be required.  However, with this sample (as well as a test I built) I am always getting the login-prompt.  Every time I press the button it will prompt for the login again (not just the first time where consent is needed).  Is this a bug or am I doing something wrong?  

Outlook is on beta channel and 17531
![image](https://github.com/OfficeDev/Office-Add-in-samples/assets/28786762/e06ce121-2ca0-4d2e-8203-0574f93393bb)

App Registration:
![image](https://github.com/OfficeDev/Office-Add-in-samples/assets/28786762/8f3136ed-17c5-4952-a051-5f4edf3da73b)
![image](https://github.com/OfficeDev/Office-Add-in-samples/assets/28786762/8d63ad00-f0d8-4504-9b1c-96eb702142a0)

Thanks!

**Comment by samantharamon** [comment]
Thanks for reaching out, @GrumpyAL. @davidchesnut, could you please investigate this?

**Comment by davidchesnut** [comment]
Hi @GrumpyAL,

Thanks for letting us know. The sample should work and once you have consented through the dialog, acquireTokenSilent should work. Can you let us know what error acquireTokenSilent is returning? Also when you are prompted to sign in again, does the sign in work and are you able to retrieve file names from OneDrive? 

Thanks!
David

**Comment by GrumpyAL** [comment]
@mattgeim,

Thanks so much for the response.  While tinkering with the sample I came up with one more question (I hope this is the appropriate place to ask).

Is it intended that this will work on Trident to support the Outlook clients that don't use edge? ([Ref](https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins#perpetual-versions-of-office-on-windows)). I'd be most concerned about 2019/2016 volume licensed from that list.  I tried to get it to run with babel/webpack but had no luck.  Just wondering what the plan is for supporting those webviews or do we just need to plan on a fallback like office dialog there? 

Additionally, I basically use ES5 right now to ensure support of IE11 webviews, so new async/await etc.  Assuming I'll have to finally bump up to ES6 to get the NAA code imported/implemented? I can't seem to find a way to load it with ES5/require and saw the CDN version stopped at 2.

Thanks again, appreciate all of your assistance.

**Comment by davidchesnut** [comment]
Hi @GrumpyAL, I don't believe you'll be able to run NAA on older Office clients using IE webview. @mattgeim please correct me if I'm wrong.

Good question on using ES5 vs ES6 and NAA compatibility. NAA is implemented in the MSAL js browser library. I recommend reaching out to the identity folks for help on that question. See the [community support and help options](https://github.com/AzureAD/microsoft-authentication-library-for-js?tab=readme-ov-file#community-help-and-support). I know sometimes you can use a [polyfill such as on 2.x](https://stackoverflow.com/questions/68345376/does-msal-2-js-works-with-ie-11/68346140#68346140), but I don't know for the latest library version.

Hope this helps!
David

**Comment by Nurou** [comment]
Could anyone please provide clarity/confirmation on this? 

>  I don't believe you'll be able to run NAA on older Office clients using IE webview

It's an important question as IE is still used by some office [versions](https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins). cc: @mattgeim @davidchesnut

**Comment by mattgeim** [comment]
> Could anyone please provide clarity/confirmation on this?
> 
> > I don't believe you'll be able to run NAA on older Office clients using IE webview
> 
> It's an important question as IE is still [used by Outlook 2016 and 2019 volume licenses](https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins) cc: @mattgeim @davidchesnut

NAA won't be supported in add-ins using Trident+/IE - The minimum version required of MSAL.js to perform NAA flows does not support Internet Explorer/Internet Explorer-based webviews.

**Comment by akrantz** [comment]
@mattgeim @davidchesnut  It would be good to clarify the requirements here for add-in developers. 

If there a way to signify in the manifest so add-ins which only want to be available on Office versions which support NAA / modern webview/browser, how do they do that? Is there a requirement set which should be used to signify this?

If the add-in wants to be able to run regardless, but have a runtime check so NAA is only used when available, and there is a fallback or error when it isn't available, how would they do that?
