### ISSUE TITLE
How to debug against outlook online account with MFA?

### ISSUE THREAD

**Issue by asifsid** [OfficeDev/Office-Add-in-samples#763]
> Note: This repo is only for questions related to its samples. If you have questions about how to use office.js or the Office developer platform, please post your question on https://stackoverflow.com. Tag your question with office-js or outlook-web-addins

**Question**

The instruction describes adding the outlook email address. But for outlook online setup where MFA is enabled, it doesn't seem like it works with that setup. How is the auth flow set up for such case?

**Comment by davidchesnut** [comment]
Hi @asifsid, which sample are you looking at? Thanks!

**Comment by asifsid** [comment]
I was looking at both

Samples\blazor-add-in\outlook-blazor-add-in

-and-

Samples\auth\Outlook-Add-in-Microsoft-Graph-ASPNET

I am getting this when I am trying to debug:


Thanks,

~Asif
________________________________

**Comment by asifsid** [comment]
Sent too soon.


________________________________

**Comment by asifsid** [comment]
I have figured out the answer.

Need to set the "Use multi-factor Auth" setting to true in the same project.
