### ISSUE TITLE
Outlook-Add-in-SSO-NAA: Questions on usage on mobile devices

### ISSUE THREAD

**Issue by GruberMarkus** [OfficeDev/Office-Add-in-samples#777]
> Note: This repo is only for questions related to its samples. If you have questions about how to use office.js or the Office developer platform, please post your question on https://stackoverflow.com. Tag your question with office-js or outlook-web-addins

**Question**

Thanks for the Outlook-Add-in-SSO-NAA sample! It works fine on Outlook for Windows.

I have a few questions regarding this example on Outlook Mobile (Android and iOS), knowing that these two platforms are not yet supported.
- Is the sample code expected to work without modifications once Android and iOS are supported?
- Is there a beta program or something comparable for iOS and Android I can join so I can test my add-in early?
- Is it safe to assume the following?
  - NAA will be fully available on all Outlook platforms before October 2024, as this is when exchange identity tokens will no longer be supported?
  - Outlook on mobile platforms will likely not get support for getAuthToken(), but for the more secure and therefore preferred NAA (nested app authentication)

Thanks in advance!

**Comment by davidchesnut** [comment]
Hi @GruberMarkus, thanks for raising these questions!

- Yes mobile will be supported by NAA (although it's not in the preview just yet. It's coming soon.) And you are correct that OBO SSO (getAuthToken) will not be updated to support mobile.
-  Ideally, the sample code should work without modifications on mobile as we want this to be as simple as possible. If there are any modifications required we will document them in the sample.
- Testing guidance is also something we're working to provide soon. Please keep an eye on the [Office Add-ins community](https://aka.ms/officeaddinscommunitycall) call and the [M365 developer blog](https://devblogs.microsoft.com/microsoft365dev) for any updates.

**Comment by GruberMarkus** [comment]
Thanks for your support!

Closing this issue.
