### ISSUE TITLE
Can we implement NAA-SSO for spam-addins?

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/Office-Add-in-samples#785]
> Note: This repo is only for questions related to its samples. If you have questions about how to use office.js or the Office developer platform, please post your question on https://stackoverflow.com. Tag your question with office-js or outlook-web-addins

**Question**

Will NAA-SSO be supported in spam addins? If so, is there a documentation or sample project we can use as reference? Thank you.

**Comment by davidchesnut** [comment]
Hi @glr0221,

It took some time but yes this is supported and the sample is here: https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Outlook-Add-in-SSO-events

Hope this helps,
David

**Comment by glr0221** [comment]
Hello again @davidchesnut ,

I looked into that link and it seems like it is an SSO-OBO flow.
Are you saying that SSO-OBO flow is the way to go for spam addins?

Thank you.

**Comment by AlexJerabek** [comment]
Hi @glr0221,

I think @davidchesnut had intended to link to this sample: https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Outlook-Event-SSO-NAA

Apologies for the confusion.
