### ISSUE TITLE
Hello World add-in doesn't work in desktop Outlook 2016

### ISSUE THREAD

**Issue by YesLetsGo** [OfficeDev/Office-Add-in-samples#786]
I launched the add-on found here using the instructions:
https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/hello-world/outlook-hello-world

The add-in works fine in Outlook on the web, but when I run in desktop Outlook it doesn't work. Taskpane starts and html is loaded, but it looks like js doesn't work.  That is, the text (This add-in will insert the text "Hello world!" in a new message) is displayed and button, but when I click it nothing happens.

Additionally, after pressing the right mouse button on taskpane and selecting view source, nothing starts.

**Comment by AlexJerabek** [comment]
Thanks for reporting this @YesLetsGo.

@samantharamon, could you please investigate?

**Comment by samantharamon** [comment]
Hi @YesLetsGo,

I tested the Hello World sample using [GitHub as a web host](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/hello-world/outlook-hello-world#run-the-sample-using-github-as-a-web-host) in Outlook on Windows (classic and new clients) and on the web. I see the inserted text after selecting the button from the task pane as expected. Are you using GitHub as a web host or are you using a localhost server?
