### ISSUE TITLE
Edit the Existing mail

### ISSUE THREAD

**Issue by SindhuChenna** [OfficeDev/Office-Add-in-samples#799]
https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/hello-world/outlook-hello-world

**Describe the bug**

On click of button getting error
Uncaught TypeError: Office.context.mailbox.item.body.setAsync is not a function
    at HTMLButtonElement.sayHello 

**To Reproduce**

1. _Go to  add-in
2. _Click on  sayHello button
3. _Scroll down to '....'_
4. _See error_ Uncaught TypeError: Office.context.mailbox.item.body.setAsync is not a function
    at HTMLButtonElement.sayHello 

**Expected behavior**

Display the required message in the email body

**Screenshots**

![Screenshot 2024-06-17 181940](https://github.com/OfficeDev/Office-Add-in-samples/assets/173063641/480bcbb2-6b81-4d8d-8f70-cdacb6c291ad)

**Environment**
- Platform [PC desktop, Mac, iOS, Office Online]: ______
- Host [Excel, Word, PowerPoint, etc.]: ______
- Office version number: ______
- Operating System: ______
- Browser (if using Office Online): ______

**Additional context**

_Add any other context about the problem here._

**Comment by AlexJerabek** [comment]
Hi @SindhuChenna,

Thanks for reporting this. Could you please share which version of Outlook you're using (web, Mac, Windows Classic, New Outlook for Windows)? Also, just to clarify, are you using the GitHub hosted version (manifest.xml), or are you running the web server on localhost (manifest-localhost.xml?

**Comment by SindhuChenna** [comment]
Hi,
New outlook for windows.
I have just copied manifest.xml and html files.

**Comment by AlexJerabek** [comment]
When you say you've "copied manifest,xml and html files", could you please elaborate? If you're building the project and running it locally, you'll need to copy everything from the repo. If you're sideloading the GitHub hosted version, you should only need the manifest.

Also, I reran the sample and could not reproduce those errors.

**Comment by SindhuChenna** [comment]
After adding  localhost.crt and localhost.key files in the folder getting the below error
 Error: Could not find certificate localhost.crt
![Screenshot (191)](https://github.com/OfficeDev/Office-Add-in-samples/assets/173063641/69b743f4-dcb5-41e4-972b-2f741f861323)

**Comment by AlexJerabek** [comment]
@exextoc, could you please take a look?

**Comment by davidchesnut** [comment]
Hi @SindhuChenna, to run the sample from localhost, you need to put the localhost.key and .crt files in the `Office-Add-in-samples\Samples\hello-world\outlook-hello-world` folder. Then you can run `http-server -S -C localhost.crt -K localhost.key --cors . -p 3000` from that same folder. Hope this helps!
