### ISSUE TITLE
Outlook.RelatedData mogic to retrieve reports and company is not implemented

### ISSUE THREAD

**Issue by bpatra** [OfficeDev/Office-Add-in-samples#8]
in _restService.js_ we have the two following functions

``` javascript
  function getCompany(mailbox){
      var deferred = $q.defer();
      var restQueryUrl = "https://localhost:44301/api/companies?$filter=substringof(Email,'" + mailbox.from.emailAddress + "')";
      $http({
        method: 'GET',
        url: restQueryUrl,
      /* etc. */
    }
```

And 

``` javascript
   function getReports(mailbox) {
        var restQueryUrl = "https://localhost:44301/api/reports?mail=" + mailbox.from.emailAddress;
        return $http({
            url: restQueryUrl,
            method: "GET",
           /* etc. */
    }
```

It seems that there is no server side logic to handle those requests. In addition, they should target the proper server. The domain and the port 44301 are hardcoded.

**Comment by ElizabethSamuel-MSFT** [comment]
@bpatra Thanks for raising this issue.

@davidchesnut Can you take a look?

Thanks.

**Comment by KelBowen** [comment]
@davidchesnut Any updates?

**Comment by davidchesnut** [comment]
Hi @bpatra, sorry, but this sample was archived. Once samples are archived we no longer maintain them. If you are still encountering any issues that the active samples aren't helping with, can you please open a new issue so we can take a look?

Thanks!
David
