### ISSUE TITLE
Outlook SSO NAA in pure JS without node.js

### ISSUE THREAD

**Issue by GruberMarkus** [OfficeDev/Office-Add-in-samples#816]
Dear Office Add-In Samples team,

Outlook on Windows only uses the runtime JS file defined in the manifest für event-based add-ins. How do you import and use msal-browser in this file without using node.js.

I am aware that import is not allowed on Outlook on Windows for event based files, so i guess it is all about bundling - but is there is simpler, more straight-forward alternative to npm/node.js?

Kind regards,

Markus

**Comment by AlexJerabek** [comment]
Hi @GruberMarkus,

Thank you for the question. @samantharamon or @exextoc, could you please provide some guidance?

**Comment by GruberMarkus** [comment]
Done: https://stackoverflow.com/questions/78753300/outlook-sso-naa-in-pure-js-without-node-js
