### ISSUE TITLE
Excel custom function on blazoraddin technique works locally but not when published on AZURE

### ISSUE THREAD

**Issue by RaoulRSV** [OfficeDev/Office-Add-in-samples#817]
Question
My project is derived from the blazorAddin template for Excel provided by [this samples](https://github.com/OfficeDev/Office-Add-in-samples/tree/main) and further from [this code](https://github.com/RaoulRSV/excel-blazor-add-in_NET7.0). The project is now well advanced except on "Excel custom functions" that work properly locally but not on Azure after publishing.

The Javascript code on "Pages.Index. Razor.Js is 
`/**
    * Disable NO$
    * @customfunction 
    * @param{number} Reference First value    
    * @returns The Reference
    */
function yoD(Reference, Behaviour) {
    var locval;
    locval = Reference;
    return locval
}
CustomFunctions.associate("YOD", yoD);>`

Functions.json is located on wwwroot
`<  "allowCustomDataForDataTypeAny": true,
  "allowErrorForDataTypeAny": true,
  "functions": [
    {
      "id": "YoD",
      "name": "YoD",
      "description": "Realise Yo$",
      "helpUrl": "http://www.contoso.com/help",
      "result": { "type": "any" },
      "parameters": [
        {
          "name": "Reference",
          "description": "First value",
          "type": "any"
        }
      ]
    }
  ]
}`

Functions.html is also located on wwwroot 

 `<!DOCTYPE html><head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta http-equiv="Expires" content="0" />
    <title></title>
    <script src="https://appsforoffice.microsoft.com/lib/1.1/hosted/custom-functions-runtime.js" type="text/javascript"></script>
    <script src="FunctionFile.js" type="text/javascript"></script>
/<head>
body>
    
    <script src="Pages/Index.razor.js" type="text/javascript"></script>
/<body>`

What is wrong ?

**Comment by AlexJerabek** [comment]
@aafvstam, could you please take a look?

**Comment by aafvstam** [comment]
@RaoulRSV Did you base this on the latest version of the Blazor Samples? The latest version has interop through the Ribbon as well as calling functions in Pages.
I don't see the code you put in your issue quotes, are you referring to the right repo in your issue?

**Comment by RaoulRSV** [comment]
@aafvstam Now, with the latest Visual Studio version, custom functions are properly working on my project. Thanks for your attention.

**Comment by RaoulRSV** [comment]
Solved. The manifest was invalid. Ie : all internet address should be  https.
