### ISSUE TITLE
outlook-spam-reporting, no reports or forward

### ISSUE THREAD

**Issue by maximevhw** [OfficeDev/Office-Add-in-samples#819]
outlook-spam-reporting

I have uploaded the sample xml to my outlook and in User reported settings it has been set that reported emails go to our secOps mailbox. Yet i dont see the mails that i report in that mailbox or in user submissions.

Or was i wrong to assume that this is its functionality

**Comment by AlexJerabek** [comment]
Hi @maximevhw,

According to the sample description, I don't believe this sample actually handles the sending of the email: "Facilitates saving a copy of the reported email to a file to submit it to your backend system for further processing." That action is intended to be handled by your webservice.

Let me tag @samantharamon to confirm.

**Comment by samantharamon** [comment]
Hi @maximevhw,

Thanks for reaching out. As Alex mentioned, the sample only shows you how to save the Base64-encoded EML format of the reported message using the `getAsFileAsync` method. However, you'll need to implement the sending of the message to your backend system. Regarding the user-reported settings you mentioned, assuming you're referring to the [moveItemTo](https://learn.microsoft.com/javascript/api/outlook/office.spamreportingeventcompletedoptions#outlook-office-spamreportingeventcompletedoptions-moveitemto-member) property of the `event.completed` call, please note that you can only move a reported message to a folder within the same mailbox from which the message was reported (see [Office.MailboxEnums.MoveSpamItemTo](https://learn.microsoft.com/en-us/javascript/api/outlook/office.spamreportingeventcompletedoptions?view=outlook-js-preview#outlook-office-spamreportingeventcompletedoptions-moveitemto-member)).
