### ISSUE TITLE
Spam addin manifest could not be loaded in Outlook.

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/Office-Add-in-samples#828]
**URL of sample**
https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/outlook-spam-reporting

**Describe the bug**
We tried to upload this manifest in one our customer environments and it failed to deploy.
It is important to note that any addin from the marketplace can be installed in the customer's environment.
However, any addin installed by deploying a manifest fails.

**To Reproduce**
We cannot reproduce internally in our environment.
We are hoping that the Microsoft team can help us determine if there is a setting in M365 environment that disables the sideloading/installing of custom apps via manifest files.

NA

**Expected behavior**
Installing an addin via manifest deploy/sideload should work. 

**Screenshots**
NA 

**Environment**
- Platform [PC desktop, Mac, iOS, Office Online]: ______
- Host [Excel, Word, PowerPoint, etc.]: ______
- Office version number: ______
- Operating System: ______
- Browser (if using Office Online): ______

**Additional context**
Again installing an addin via manifest file fails. Installing addin via the marketplace works. 
They have an existing Microsoft inquiry with case # : 2407170040011584

Thank you.

**Comment by AlexJerabek** [comment]
Thanks for reporting this @glr0221.

@samantharamon, could you please investigate this?

**Comment by samantharamon** [comment]
Hi @glr0221,

Your customer may not have the My Custom Apps role assigned to their user accounts. For information on this user role, see [Specify the administrators and users who can install and manage add-ins for Outlook in Exchange Online](https://learn.microsoft.com/exchange/clients-and-mobile-in-exchange-online/add-ins-for-outlook/specify-who-can-install-and-manage-add-ins#user-roles).

**Comment by glr0221** [comment]
Thank you @samantharamon. I will try to advise our customer about this. Thank you again.

**Comment by samantharamon** [comment]
No problem. Hope it resolves the issue they're experiencing. I'll go ahead and close this issue, but if your customer is still unable to sideload the manifest even after the suggested fix, please reopen this issue.

**Comment by glr0221** [comment]
Thank you @samantharamon @AlexJerabek . I will let you know what we find out. Thanks again.

**Comment by glr0221** [comment]
Hello @samantharamon @AlexJerabek ,

Our customer enabled the settings for custom apps and was still unable to sideload the addin. These are the settings they enabled for testing : 

<img width="554" alt="image" src="https://github.com/user-attachments/assets/4d23f6b7-718c-4837-ac61-2fcfcc88e9b9">

Any other advice we can share with them? 

Again, Thank you very much.

**Comment by samantharamon** [comment]
Hi @glr0221,

Thanks for the update. If I'm not mistaken, the Org Custom Apps role only allows an admin to install and manage add-ins in their organization. They would still need to assign the necessary user role (My Custom Apps) to the account their using for testing add-ins.

![The My Custom Apps user role is checked.](https://github.com/user-attachments/assets/1318ee6c-099b-4d4f-81da-e80709cd921c)

**Comment by glr0221** [comment]
Hello @samantharamon,

I got word from our customer. Seems like, it is working now for them. Thank you so much for your patience and support.

Again, thank you. Closing this ticket now.

**Comment by samantharamon** [comment]
That's awesome news! Thanks for the update, @glr0221.
