### ISSUE TITLE
Feature request: Please provide a sample showing use of NAA in a launch event on Classic Outlook on Windows

### ISSUE THREAD

**Issue by GruberMarkus** [OfficeDev/Office-Add-in-samples#831]
Classic Outlook on Windows is very picky on JavaScript code.

Add-ins that run flawlessly on every other flavor of Outlook (Web, Classic and New on Mac, Android, iOS, New on Windows) often do not work on Classic Outlook on Windows.

My understanding is that Webpack and Babel should take care of this by bundling and transpiling JS code into a format that can be used on every Outlook variation.

I was not able to find a single launch event sample that showed how to correctly use Webpack and Babel for JS code associated with a launch event: They all circumvent the problem by just copying the original source file, without getting it touched by Webpack and Babel.

I have a working example combining NAA and a launch event, that works fine on every single flavor of Outlook, but not on Classic Outlook on Windows.

So, I am looking for an example that answers the following two questions:
- How to correctly configure Webpack and Babel so that the resulting JS file can be used in a launch event on Classic Outlook on Windows?
- How to bundle "@azure/msal-browser" so that it can be used in a launch event on Classic Outlook on Windows?

# Reproduction steps
The following steps take an existing example to show what I mean. The example only covers the launch event topic, but does not combine it with the NAA topic of importing a module.
1. Download the official Microsoft add-in sample from https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/outlook-set-signature
2. Stop Outlook
3. End pross msoadfsb.exe, if it exists
4. Clear "%LOCALAPPDATA%\Microsoft\Office\16.0\Wef\", "%userprofile%\AppData\Local\Packages\Microsoft.Win32WebViewHost_cw5n1h2txyewy\AC\#!123\INetCache\" and "%userprofile%\AppData\Local\Microsoft\Outlook\HubAppFileCache"
5. Switch to the root of "outlook-set-signature"
6. npm run start:xml
7. Outlook starts
8. Confige the add-in once (the config is stored in the mailbox for later use): Create a new email, click on "Set my signature" in the ribbon, Save, assign on of the template to "New mail", click on Save, close the new email
9. Create a new email: The signature will be added.
10. npm stop
11. Repeat steps 2-10 as often as you wish, it will always work (there is no need to repeat step 8)

Now to the tricky part:
12. Repeat steps 2-5
13. in webpack.config.js, delete or comment the following lines:
   ```
   {
     from: "src/runtime/Js/autorunshared.js",
     to: "[name]" + "[ext]",
   },
   ```
14. npm run start:xml
15. Outlook starts
16. Create a new email: The signature will NOT be added

What happens is that the Outlook launch event is bound to code running in autorunshared.js. In the original configuration of the sample, autorunshared.js is just copied to the distribution folder as is, without webpack even touching it.

When you do the comment/delete stuff in step 13, this copy is disabled and the webpack modified version of autorunshared.js is used. You can see that when looking at your dist folder after building, or when looking at the associated bundle.js file in the "%LOCALAPPDATA%\Microsoft\Office\16.0\Wef\" folder structure.

Webpack and/or Babel do something to the code that the JS engine used by the OnMessageCompose launch event in Classic Outlook on Windows is not able to work with. At the same time, the very same Webpack/Babel modified code works fine on Outlook Web/Android/iOS/Mac.

How is this supposed to work with production code being deployed to customers? Webpack offers at least some sort of code protection, and Outlook Web/Android/iOS/Mac can even handle JS code being obfuscated by multiple tools.

Even more important: Microsoft wants us all to switch from legacy tokens to Nested App Authentication (NAA) in add-ins as soon as possible (I am aware that the timelines have been moved from October 2024 shortly). Using NAA requires `import { createNestablePublicClientApplication } from "@azure/msal-browser";`, even for launch events.

**Comment by AlexJerabek** [comment]
Thanks for this feedback @GruberMarkus.

Tagging @pinverso and @davidchesnut to investigate.

**Comment by GruberMarkus** [comment]
Closing as the code is now available via PR https://github.com/OfficeDev/Office-Add-in-samples/pull/832.
