### ISSUE TITLE
Outlook add-ins attachmnet Demo web

### ISSUE THREAD

**Issue by pelepelex** [OfficeDev/Office-Add-in-samples#837]
> Note: This repo is only for questions related to its samples. If you have questions about how to use office.js or the Office developer platform, please post your question on https://stackoverflow.com. Tag your question with office-js or outlook-web-addins

**Question**

_Ask your question here._

I'm getting this error Server side error: An error occurred calling Microsoft Graph
Details: null

**Comment by AlexJerabek** [comment]
Hi @pelepelex,

Just to clarify, are you talking about this sample [Encrypt attachments, process meeting request attendees, and react to appointment date/time changes using Outlook event-based activation](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/outlook-encrypt-attachments )?
