### ISSUE TITLE
Unable to sideload sample "Outlook-Add-in-SSO-NAA"

### ISSUE THREAD

**Issue by malnoxon** [OfficeDev/Office-Add-in-samples#868]
I've been following the instructions at https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Outlook-Add-in-SSO-NAA to get the sample running as a reference point for eventually migrating my own project off legacy Exchange tokens.

I'm running into issues at the "Run the sample" step where I need to sideload the add-in. `npm run start` fails with 
```
Error: Unable to start debugging.
Error: Unable to sideload the Office Add-in. 
Error: Sideload to the Outlook app is not supported.
```
Which is mostly expected as I'm still working on confirming that I have an appropriate insider level for the NAA preview features for Outlook for Mac so I could see that blocking the sideload.

I'm also having a similar issue though when running `npm run dev-server` (which seems to work) and trying to sideload into outlook in my browser (via https://aka.ms/olksideload) which AFAICT should support NAA already. When I do that it just fails with a generic "Add-in installation failed." message.

**Comment by AlexJerabek** [comment]
Thanks for reporting this. Could you please confirm your Outlook build number?

@codexeon, any thoughts?

**Comment by malnoxon** [comment]
Microsoft Outlook for Mac
Version 16.74 (23061100)
Microsoft 365 Subscription

though it's the web version's behavior that's surprising to me (Outlook on the Web per https://support.microsoft.com/en-us/office/what-version-of-outlook-do-i-have-b3a9568c-edb5-42b9-9825-d48d82b2257c#ID0EBBH=Web)

**Comment by davidchesnut** [comment]
Hi @malnoxon,

NAA is GA on Mac version 16.89. All the platform availability information is at [Nested app auth requirement set](https://learn.microsoft.com/javascript/api/requirement-sets/common/nested-app-auth-requirement-sets).

Looks like the launch.json file only includes options for debugging on Windows. I'll check into if this can be updated for Mac. For now, the workaround would be to use the [Mac debugging info from our docs](https://learn.microsoft.com/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac).

I'm not sure why you see an error sideloading using the browser. I tried sideloading the sample's manifest and it works. If you still see that issue can you try a different browser just to see if maybe it's related to browser settings?

Thanks!
David

**Comment by malnoxon** [comment]
Tried again today and it sideloaded successfully in both chrome and firefox. Don't know what caused it to fail my previous times and can't reproduce it anymore.
