### ISSUE TITLE
Shortcuts Add-in not working for Word

### ISSUE THREAD

**Issue by samantharamon** [OfficeDev/Office-Add-in-samples#896]
### Discussed in https://github.com/OfficeDev/Office-Add-in-samples/discussions/895

<div type='discussions-op-text'>

<sup>Originally posted by **rr-epona** December  3, 2024</sup>
Hey all,

Custom keyboard shortcuts for Word Add-ins, have been supported for a few months now, but it is giving me trouble.

From [office-keyboard-shortcuts](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/office-keyboard-shortcuts), the sample code works for Excel, sideloaded in desktop and web, either run from GitHub or localhost.
When attempting the same cases with Word, the add-in loads successfully, but none of the shortcuts trigger an action in the add-in.

The "manifest.xml" should work directly when sideloaded. Does this work for anybody else in Word?

Mainly curious about making this work for Word in web.</div>

**Comment by thibaultwillmann** [comment]
@samantharamon I'm curious when can we expect stable support on Word on the Web? Currently `Office.actions.getShortcuts()` only returns the configured shortcuts the first time opening the task pane after side loading the Add-In and the keyboard shortcuts never work.

**Comment by samantharamon** [comment]
Hi @thibaultwillmann,

We're unable to provide a specific date at this time, but we're working on rolling out support for keyboard shortcuts in Word on the web. I recommend periodically checking [Add custom keyboard shortcuts to your Office Add-ins](https://learn.microsoft.com/office/dev/add-ins/design/keyboard-shortcuts) and tuning into the monthly [Office Add-ins community call](https://learn.microsoft.com/office/dev/add-ins/overview/office-add-ins-community-call) for updates on support.

**Comment by thibaultwillmann** [comment]
Thank you!!
