### ISSUE TITLE
Outlook | Simple example show a Popup with external HTML content?

### ISSUE THREAD

**Issue by DunhamGitHub** [OfficeDev/Office-Add-in-samples#900]
**Is there a Outlook sample to create a simple button that pops up a window, which loads content from an external HTML?**

I have used the "Outlook spam reporting" Demo, which does popup a window, but a) the button is not in the message header and b) the content of the popup is defined in the manifest (xml).
(Maybe it's just me but, have been a JS dev for over 10years, ...struggling to find appropriate documentation)

Read and created tests for following:
https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/outlook-spam-reporting
https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/hello-world/outlook-hello-world
https://learn.microsoft.com/en-us/office/dev/add-ins/develop/create-addin-commands

<img width="735" alt="SCR-20241209-houk" src="https://github.com/user-attachments/assets/d94924f7-b4cc-4deb-b4f0-76120d709905">

**Comment by DunhamGitHub** [comment]
> Hi @DunhamGitHub. Thanks for reaching out. There is currently no support for creating a button directly in the message interface like what you have in the screenshot you shared. As an alternative, would the [MoreInfo element](https://learn.microsoft.com/en-us/javascript/api/manifest/moreinfo) work for your scenario? 

Perhaps, can I freely design the contents inside of the popup? (Textfield, Numberonly-field, Datepicker)?

**Comment by samantharamon** [comment]
You can customize the content of the following [elements](https://learn.microsoft.com/javascript/api/manifest/preprocessingdialog) of the spam-reporting dialog.
- The title.
- The description/message.
- The link that appears below the description.
- The reporting options (these currently use checkboxes, but we're expanding this in the future to include support for radio buttons).
- A text field to get more information from users.

However, you can't design the content, i.e., the elements have fixed locations on the dialog and you can't change the element design type.
